spring:
  application.name: versionapi
  datasource:
    url: jdbc:postgresql://localhost/versioningdb
    username: versionuser
    password: 12345

  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml
  jackson:
    serialization:
      write-dates-as-timestamps: true

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
  endpoint:
    health.enabled: true

server.use-forward-headers: true

server:
  port: 80

logging:
  pattern:
    console: "{\"time\": \"%d\", \"level\": \"%p\", \"source\": \"%logger{63}:%L\", \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\"}%n"
