---
version: 2
plan:
  project-key: BRAIN
  key: H5PV
  name: H5PViewer
stages:
  - Build:
    - Build docker image and run tests

Build docker image and run tests:
  tasks:
    - script:
        interpreter: shell
        scripts:
          - '#!/bin/bash'

          - 'set -eux'

          - 'dockerapptag="dockerregistry.cerpus.net/cerpus/h5pviewer-app:${bamboo.planKey}-${bamboo.buildNumber}"'
          - 'dockerinittag="dockerregistry.cerpus.net/cerpus/h5pviewer-init:${bamboo.planKey}-${bamboo.buildNumber}"'
          - 'dockerphpunittag="h5pviewer-phpunit:${bamboo.planKey}-${bamboo.buildNumber}"'
          - 'dockerdeploytag="dockerregistry.cerpus.net/cerpus/h5pviewer-deploy:${bamboo.planKey}-${bamboo.buildNumber}"'
          - 'dockerfpmtag="dockerregistry.cerpus.net/cerpus/h5pviewer-fpm:${bamboo.planKey}-${bamboo.buildNumber}"'
          - 'dockercrontag="dockerregistry.cerpus.net/cerpus/h5pviewer-cron:${bamboo.planKey}-${bamboo.buildNumber}"'
          - 'dockeredstepmessagestag="dockerregistry.cerpus.net/cerpus/h5pviewer-edstepmessages:${bamboo.planKey}-${bamboo.buildNumber}"'
          - 'dockerhorizonqueuetag="dockerregistry.cerpus.net/cerpus/h5pviewer-horizonqueue:${bamboo.planKey}-${bamboo.buildNumber}"'
          - 'echo "cerpus.dockerimage=$dockerapptag" > dockervars.properties'
          - 'echo "cerpus.dockerstartupimage=$dockerdeploytag" >> dockervars.properties'
          - 'echo "cerpus.dockerinitimages=init=$dockerinittag" >> dockervars.properties'
          - 'echo "cerpus.dockeradditionalimages=cron=$dockercrontag,edstepmessages=$dockeredstepmessagestag,horizonqueue=$dockerhorizonqueuetag,phpfpm=$dockerfpmtag" >> dockervars.properties'

          - 'docker build --tag $dockerphpunittag --target test .'
          - 'docker build --tag $dockerapptag --target app .'
          - 'docker build --tag $dockerinittag --target init .'
          - 'docker build --tag $dockerfpmtag --target phpfpm .'
          - 'docker build --tag $dockercrontag --target cron .'
          - 'docker build --tag $dockerdeploytag --target deploy .'
          - 'docker build --tag $dockeredstepmessagestag --target edstepmessages .'
          - 'docker build --tag $dockerhorizonqueuetag --target horizonqueue .'
          - 'mkdir -p test-storage-volume'
          - 'docker run --rm --name "phpunit-${bamboo.planKey}-${bamboo.buildNumber}" --volume `pwd`"/test-storage-volume:/storage" "$dockerphpunittag"'
          - 'for i in $dockerapptag $dockerinittag $dockercrontag $dockerdeploytag $dockeredstepmessagestag $dockerhorizonqueuetag $dockerapptag $dockerfpmtag; do docker push $i; done'
    - inject-variables:
        file: dockervars.properties
        scope: RESULT
        namespace: inject
  final-tasks:
    - test-parser:
        type: junit
        test-results: test-storage-volume/test-report.xml
  requirements:
    - Docker
