component_management:
  individual_components:
    - component_id: contentauthor
      name: Content Author
      paths:
        - "sourcecode/apis/contentauthor/**"
    - component_id: hub
      name: Hub
      paths:
        - "sourcecode/hub/**"

comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment
