version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    # the other ecosystems are labeled by labeler
    labels: [dependencies]

  - package-ecosystem: composer
    directory: /sourcecode/hub
    schedule:
      interval: weekly
    labels: []

  - package-ecosystem: npm
    directory: /sourcecode/hub
    schedule:
      interval: weekly
    labels: []

  - package-ecosystem: composer
    directory: /sourcecode/apis/contentauthor
    schedule:
      interval: weekly
    labels: []

  - package-ecosystem: npm
    directory: /sourcecode/apis/contentauthor
    schedule:
      interval: weekly
    labels: []
