version: 2

# labels should be handled by labeler workflow

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: []

  - package-ecosystem: composer
    directory: /sourcecode/hub
    schedule:
      interval: weekly
    labels: []

  - package-ecosystem: npm
    directory: /sourcecode/hub
    schedule:
      interval: weekly
    labels: []

  - package-ecosystem: composer
    directory: /sourcecode/apis/contentauthor
    schedule:
      interval: weekly
    labels: []

  - package-ecosystem: npm
    directory: /sourcecode/apis/contentauthor
    schedule:
      interval: weekly
    labels: []
