version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: composer
    directory: /sourcecode/hub
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /sourcecode/hub
    schedule:
      interval: weekly

  - package-ecosystem: composer
    directory: /sourcecode/apis/contentauthor
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /sourcecode/apis/contentauthor
    schedule:
      interval: weekly
