apiVersion: v1
kind: ConfigMap
metadata:
  name: "common-v2"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/resource-policy": "keep"
data:
  NODE_ENV: "production"

  EDLIBCOMMON_API_URL: {{ .Values.urls.api | quote }}
  EDLIBCOMMON_WWW_URL: {{ .Values.urls.www | quote }}

  EDLIBCOMMON_RESOURCE_EMBED_URL: "{{ .Values.urls.www }}/s/resources/<resourceId>"

  EDLIBCOMMON_EXTERNALAUTH_ADAPTER: {{ .Values.masterAuth.adapter | quote }}
  EDLIBCOMMON_EXTERNALAUTH_JWKS_ENDPOINT: {{ .Values.masterAuth.wellKnownEndpoint | quote }}
  EDLIBCOMMON_EXTERNALAUTH_ISSUER: {{ .Values.masterAuth.issuer | quote }}

{{ if eq .Values.masterAuth.adapter "auth0" }}
  EDLIBCOMMON_EXTERNALAUTH_ADAPTER_AUTH0_DOMAIN: {{ .Values.masterAuth.auth0.domain | quote }}
  EDLIBCOMMON_EXTERNALAUTH_ADAPTER_AUTH0_CLIENTID: {{ .Values.masterAuth.auth0.clientId | quote }}
  EDLIBCOMMON_EXTERNALAUTH_ADAPTER_AUTH0_AUDIENCE: {{ .Values.masterAuth.auth0.audience | quote }}
  EDLIBCOMMON_EXTERNALAUTH_PROPERTYPATH_ID: {{ .Values.masterAuth.propertyPaths.id | quote }}
  EDLIBCOMMON_EXTERNALAUTH_PROPERTYPATH_NAME: {{ .Values.masterAuth.propertyPaths.name | quote }}
  EDLIBCOMMON_EXTERNALAUTH_PROPERTYPATH_EMAIL: {{ .Values.masterAuth.propertyPaths.email | quote }}
{{ end }}
{{ if eq .Values.masterAuth.adapter "cerpusAuth" }}
  EDLIBCOMMON_EXTERNALAUTH_ADAPTER_CERPUSAUTH_URL: {{ .Values.masterAuth.cerpusAuth.url | quote }}
  EDLIBCOMMON_EXTERNALAUTH_ADAPTER_CERPUSAUTH_CLIENTID: {{ .Values.masterAuth.cerpusAuth.clientId | quote }}
  EDLIBCOMMON_EXTERNALAUTH_ADAPTER_CERPUSAUTH_SECRET: {{ .Values.masterAuth.cerpusAuth.secret | quote }}
{{ end }}

  EDLIBCOMMON_DB_HOST: {{ .Values.services.mysql.host | quote }}
  EDLIBCOMMON_DB_USER: {{ .Values.services.mysql.user | quote }}
  EDLIBCOMMON_DB_PORT: {{ .Values.services.mysql.port | quote }}
  EDLIBCOMMON_DB_CHARSET: {{ .Values.services.mysql.charset | quote }}

  EDLIBCOMMON_REDIS_URL: {{ .Values.services.redis.url | quote }}
  EDLIBCOMMON_REDIS_HOST: {{ .Values.services.redis.host | quote }}
  EDLIBCOMMON_REDIS_PORT: {{ .Values.services.redis.port | quote }}

  EDLIBCOMMON_ELASTICSEARCH_URL: {{ .Values.services.elasticsearch.url | quote }}

  EDLIBCOMMON_RABBITMQ_URL: {{ .Values.services.rabbitmq.url | quote }}
  EDLIBCOMMON_RABBITMQ_HOST: {{ .Values.services.rabbitmq.host | quote }}
  EDLIBCOMMON_RABBITMQ_PORT: {{ .Values.services.rabbitmq.port | quote }}
  EDLIBCOMMON_RABBITMQ_USER: {{ .Values.services.rabbitmq.user | quote }}
  EDLIBCOMMON_RABBITMQ_PASSWORD: {{ .Values.services.rabbitmq.password | quote }}
  EDLIBCOMMON_RABBITMQ_SECURE: {{ .Values.services.rabbitmq.secure | quote }}

  EDLIBCOMMON_EMBEDLY_KEY: {{ .Values.services.embedly.key | quote }}

  EDLIBCOMMON_CONTENTAUTHOR_URL: {{ .Values.contentauthor.url | quote }}
  EDLIBCOMMON_CONTENTAUTHOR_CONSUMER_KEY: {{ .Values.contentauthor.h5pConsumerKey | quote }}
  EDLIBCOMMON_CONTENTAUTHOR_CONSUMER_SECRET: {{ .Values.contentauthor.h5pConsumerSecret | quote }}
  EDLIBCOMMON_CONTENTAUTHOR_INTERNAL_KEY: {{ .Values.contentauthor.internalKey | quote }}

  {{/*  Features */}}
  EDLIBCOMMON_FEATURE_AUTO_UPDATE_LTI_USAGE: {{ .Values.features.enableAutoLinking | quote }}

  {{/*  @todo try to remove below variables. They are either useless, or we should find alternatives */}}
  DEPLOYMENT_ENVIRONMENT: {{ .Values.deploymentEnvironment | quote }}
  REACT_APP_API_URL: {{ .Values.urls.api | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "common-v2"
type: Opaque
data:
  EDLIBCOMMON_DB_PASSWORD: {{ .Values.services.mysql.password | b64enc | quote }}
