<?php

namespace Tests\Seeds;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TestH5PSeeder extends Seeder
{
    public function run()
    {
        $this->h5pLibraries();
        $this->h5pLibrariesLibraries();
    }

    public function h5pLibraries()
    {
        DB::table("h5p_libraries")->insert(
            [
                [
                    'id' => '1',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'Drop',
                    'title' => 'Drop',
                    'major_version' => '1',
                    'minor_version' => '0',
                    'patch_version' => '1',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'js/drop.min.js',
                    'preloaded_css' => 'css/drop-theme-arrows-bounce.min.css',
                    'drop_library_css' => '',
                    'semantics' => '',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '3',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'FontAwesome',
                    'title' => 'Font Awesome',
                    'major_version' => '4',
                    'minor_version' => '5',
                    'patch_version' => '1',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => '',
                    'preloaded_css' => 'h5p-font-awesome.min.css',
                    'drop_library_css' => '',
                    'semantics' => '',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '37',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.JoubelUI',
                    'title' => 'Joubel UI',
                    'major_version' => '1',
                    'minor_version' => '2',
                    'patch_version' => '7',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'js/joubel-help-dialog.js, js/joubel-message-dialog.js, js/joubel-progress-circle.js, js/joubel-simple-rounded-button.js, js/joubel-speech-bubble.js, js/joubel-throbber.js, js/joubel-tip.js, js/joubel-slider.js, js/joubel-score-bar.js, js/joubel-progressbar.js, js/joubel-ui.js',
                    'preloaded_css' => 'css/joubel-help-dialog.css, css/joubel-message-dialog.css, css/joubel-progress-circle.css, css/joubel-simple-rounded-button.css, css/joubel-speech-bubble.css, css/joubel-tip.css, css/joubel-slider.css, css/joubel-score-bar.css, css/joubel-progressbar.css, css/joubel-ui.css',
                    'drop_library_css' => '',
                    'semantics' => '',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '39',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.MarkTheWords',
                    'title' => 'Mark the Words',
                    'major_version' => '1',
                    'minor_version' => '5',
                    'patch_version' => '5',
                    'runnable' => '1',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'mark-the-words.js',
                    'preloaded_css' => 'mark-the-words.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"label": "Task description","name": "taskDescription","type": "text","widget": "html","description": "Describe how the user should solve the task.","placeholder": "Click on all the verbs in the text that follows.","enterMode": "p","tags": ["strong","em","u","a","ul","ol","h2","h3","hr"]},{"label": "Textfield","name": "textField","type": "text","widget": "html","tags": ["p", "br", "strong", "em"],"placeholder": "This is an answer: *answer*.","description": "Marked words are added with an asterix (*). An asterix may be escaped with another asterix, resulting in ** = *. Example: The correct words are marked with like this: *correctword*, and a character asterix is written like this: **."},{"label": "Text for \\"Check\\" button","name": "checkAnswerButton","type": "text","default": "Check","common": true},{"label": "Text for \\"Retry\\" button","name": "tryAgainButton","type": "text","default": "Retry","common": true},{"label": "Text for \\"Show solution\\" button","name": "showSolutionButton","type": "text","default": "Show solution","common": true},{"label": "Feedback text","name": "score","type": "text","default": "You got @score of @total points.","placeholder": "You got @score of @total points.","description": "Feedback text, variables available: @score @total @correct @wrong @missed. Example: \'Score : @score of @total, correct: @correct, wrong: @wrong, missed: @missed . \'","common": true},{"name": "behaviour","type": "group","label": "Behavioural settings.","description": "These options will let you control how the task behaves.","optional": true,"fields": [{"name": "enableRetry","type": "boolean","label": "Enable \\"Retry\\"","default": true},{"name": "enableSolutionsButton","type": "boolean","label": "Enable \\"Show solution\\" button","default": true}]}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '43',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.Question',
                    'title' => 'Question',
                    'major_version' => '1',
                    'minor_version' => '1',
                    'patch_version' => '7',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'scripts/question.js',
                    'preloaded_css' => 'styles/question.css',
                    'drop_library_css' => '',
                    'semantics' => '',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '54',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.Transition',
                    'title' => 'Transition',
                    'major_version' => '1',
                    'minor_version' => '0',
                    'patch_version' => '2',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'transition.js',
                    'preloaded_css' => '',
                    'drop_library_css' => '',
                    'semantics' => '',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '72',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5PEditor.VerticalTabs',
                    'title' => 'H5P Editor Vertical Tabs',
                    'major_version' => '1',
                    'minor_version' => '1',
                    'patch_version' => '3',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'vertical-tabs.js',
                    'preloaded_css' => 'vertical-tabs.css',
                    'drop_library_css' => '',
                    'semantics' => '',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '76',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'Tether',
                    'title' => 'Tether',
                    'major_version' => '1',
                    'minor_version' => '0',
                    'patch_version' => '1',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'scripts/tether.min.js',
                    'preloaded_css' => 'styles/tether.min.css',
                    'drop_library_css' => '',
                    'semantics' => '',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '83',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'jQuery.ui',
                    'title' => 'UI',
                    'major_version' => '1',
                    'minor_version' => '10',
                    'patch_version' => '14',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'js/jquery-ui.js',
                    'preloaded_css' => 'development-bundle/themes/base/jquery-ui.css',
                    'drop_library_css' => '',
                    'semantics' => '',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '86',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'FontAwesome',
                    'title' => 'Font Awesome',
                    'major_version' => '4',
                    'minor_version' => '1',
                    'patch_version' => '2',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => '',
                    'preloaded_css' => 'font-awesome.css',
                    'drop_library_css' => '',
                    'semantics' => '',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '90',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.MarkTheWords',
                    'title' => 'Mark the Words',
                    'major_version' => '1',
                    'minor_version' => '6',
                    'patch_version' => '7',
                    'runnable' => '1',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'scripts/keyboard-nav.js, scripts/xAPI-generator.js, scripts/word.js, scripts/mark-the-words.js',
                    'preloaded_css' => 'styles/mark-the-words.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"label": "Task description","importance": "high","name": "taskDescription","type": "text","widget": "html","description": "Describe how the user should solve the task.","placeholder": "Click on all the verbs in the text that follows.","enterMode": "p","tags": ["strong","em","u","a","ul","ol","h2","h3","hr"]},{"label": "Textfield","importance": "high","name": "textField","type": "text","widget": "html","tags": ["p","br","strong","em"],"placeholder": "This is an answer: *answer*.","description": "Marked words are added with an asterix (*). An asterix may be escaped with another asterix, resulting in ** = *. Example: The correct words are marked with like this: *correctword*, and a character asterix is written like this: **."},{"label": "Text for \\"Check\\" button","importance": "low","name": "checkAnswerButton","type": "text","default": "Check","common": true},{"label": "Text for \\"Retry\\" button","importance": "low","name": "tryAgainButton","type": "text","default": "Retry","common": true},{"label": "Text for \\"Show solution\\" button","importance": "low","name": "showSolutionButton","type": "text","default": "Show solution","common": true},{"label": "Feedback text","importance": "low","name": "score","type": "text","default": "You got @score of @total points","placeholder": "You got @score of @total points","description": "Feedback text, variables available: @score @total @correct @wrong @missed. Example: \'Score : @score of @total, correct: @correct, wrong: @wrong, missed: @missed . \'","common": true},{"name": "behaviour","importance": "low","type": "group","label": "Behavioural settings.","description": "These options will let you control how the task behaves.","optional": true,"fields": [{"name": "enableRetry","type": "boolean","label": "Enable \\"Retry\\"","importance": "low","default": true},{"name": "enableSolutionsButton","type": "boolean","label": "Enable \\"Show solution\\" button","importance": "low","default": true}]},{"label": "Correct answer text","importance": "low","name": "correctAnswer","type": "text","default": "Correct!","description": "Text used to indicate that an answer is correct","common": true},{"label": "Incorrect answer text","importance": "low","name": "incorrectAnswer","type": "text","default": "Incorrect!","description": "Text used to indicate that an answer is incorrect","common": true},{"label": "Missed answer text","importance": "low","name": "missedAnswer","type": "text","default": "Missed!","description": "Text used to indicate that an answer is missing","common": true},{"label": "Description for Display Solution","importance": "low","name": "displaySolutionDescription","type": "text","default": "Task is updated to contain the solution.","description": "This text tells the user that the tasks has been updated with the solution.","common": true}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '92',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.Question',
                    'title' => 'Question',
                    'major_version' => '1',
                    'minor_version' => '2',
                    'patch_version' => '2',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'scripts/question.js',
                    'preloaded_css' => 'styles/question.css',
                    'drop_library_css' => '',
                    'semantics' => '',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '121',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.SimpleMultiChoice',
                    'title' => 'Simple Multi Choice',
                    'major_version' => '1',
                    'minor_version' => '1',
                    'patch_version' => '2',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'dist/dist.js',
                    'preloaded_css' => 'dist/styles.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"name": "question","label": "Question","importance": "high","type": "text"},{"name": "inputType","label": "Multiple choice type","importance": "high","type": "select","options": [{"label": "Multiple answers","value": "checkbox"},{"label": "Single answer","value": "radio"}],"default": "checkbox"},{"name": "alternatives","label": "Answer alternatives","type": "list","importance": "high","entity": "Alternative","min": 2,"field": {"type": "group","name": "alternative","label": "Alternative","fields": [{"name": "text","label": "Text","importance": "high","type": "text"},{"name": "feedback","type": "group","label": "Feedback","importance": "low","optional": true,"fields": [{"name": "chosenFeedback","type": "text","widget": "html","label": "Message displayed if answer is selected","importance": "low","description": "Message will appear below the answer on \\"continue\\" if this answer is selected.","optional": true,"tags": ["strong","em","sub","sup","a"]},{"name": "notChosenFeedback","type": "text","widget": "html","label": "Message displayed if answer is not selected","importance": "low","description": "Message will appear below the answer on \\"continue\\" if this answer is not selected.","optional": true,"tags": ["strong","em","sub","sup","a"]}]}]}}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '140',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.JoubelUI',
                    'title' => 'Joubel UI',
                    'major_version' => '1',
                    'minor_version' => '1',
                    'patch_version' => '3',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'js/joubel-help-dialog.js, js/joubel-message-dialog.js, js/joubel-progress-circle.js, js/joubel-simple-rounded-button.js, js/joubel-speech-bubble.js, js/joubel-throbber.js, js/joubel-tip.js, js/joubel-ui.js',
                    'preloaded_css' => 'css/joubel-help-dialog.css, css/joubel-message-dialog.css, css/joubel-progress-circle.css, css/joubel-simple-rounded-button.css, css/joubel-speech-bubble.css, css/joubel-tip.css, css/joubel-ui.css',
                    'drop_library_css' => '',
                    'semantics' => '',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '160',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.MultiChoice',
                    'title' => 'Multiple Choice',
                    'major_version' => '1',
                    'minor_version' => '9',
                    'patch_version' => '2',
                    'runnable' => '1',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'js/multichoice.js',
                    'preloaded_css' => 'css/multichoice.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"name": "media","type": "group","label": "Media","importance": "medium","fields": [{"name": "type","type": "library","label": "Type","importance": "medium","options": ["H5P.Image 1.0","H5P.Video 1.3"],"optional": true,"description": "Optional media to display above the question."}]},{"name": "question","type": "text","importance": "medium","widget": "html","label": "Question","enterMode": "p","tags": ["strong","em","sub","sup","h2","h3"]},{"name": "answers","type": "list","importance": "high","label": "Available options","entity": "option","min": 1,"defaultNum": 2,"field": {"name": "answer","type": "group","label": "Option","importance": "high","fields": [{"name": "text","type": "text","importance": "medium","widget": "html","label": "Text","tags": ["strong","em","sub","sup"]},{"name": "correct","type": "boolean","label": "Correct","importance": "low"},{"name": "tipsAndFeedback","type": "group","label": "Tips and feedback","importance": "low","optional": true,"fields": [{"name": "tip","type": "text","widget": "html","label": "Tip text","importance": "low","description": "Hint for the user. This will appear before user checks his answer/answers.","optional": true,"tags": ["p","br","strong","em","a"]},{"name": "chosenFeedback","type": "text","widget": "html","label": "Message displayed if answer is selected","importance": "low","description": "Message will appear below the answer on \"check\" if this answer is selected.","optional": true,"tags": ["strong","em","sub","sup","a"]},{"name": "notChosenFeedback","type": "text","widget": "html","label": "Message displayed if answer is not selected","importance": "low","description": "Message will appear below the answer on \"check\" if this answer is not selected.","optional": true,"tags": ["strong","em","sub","sup","a"]}]}]}},{"name": "UI","type": "group","label": "User interface translations for multichoice","importance": "low","common": true,"fields": [{"name": "checkAnswerButton","type": "text","label": "Check answer button label","importance": "low","default": "Check"},{"name": "showSolutionButton","type": "text","label": "Show solution button label","importance": "low","default": "Show solution"},{"name": "tryAgainButton","type": "text","label": "Retry button label","importance": "low","default": "Retry","optional": true},{"name": "tipsLabel","type": "text","label": "Tip label","importance": "low","default": "Show tip","optional": true},{"name": "correctText","type": "text","label": "Correct answer feedback","importance": "low","optional": true,"deprecated": true},{"name": "almostText","type": "text","label": "Almost correct answer feedback","importance": "low","optional": true,"deprecated": true},{"name": "wrongText","type": "text","label": "Not correct answer feedback","importance": "low","optional": true,"deprecated": true},{"name": "scoreBarLabel","type": "text","label": "Score Bar Label","importance": "low","default": "Score","optional": true},{"name": "tipAvailable","type": "text","label": "Tip Available (not displayed)","importance": "low","default": "Tip available","description": "Accessibility text used for readspeakers","optional": true},{"name": "feedbackAvailable","type": "text","label": "Feedback Available (not displayed)","importance": "low","default": "Feedback available","description": "Accessibility text used for readspeakers","optional": true},{"name": "readFeedback","type": "text","label": "Read Feedback (not displayed)","importance": "low","default": "Read feedback","description": "Accessibility text used for readspeakers","optional": true,"deprecated": true},{"name": "wrongAnswer","type": "text","label": "Wrong Answer (not displayed)","importance": "low","default": "Wrong answer","description": "Accessibility text used for readspeakers","optional": true,"deprecated": true},{"name": "correctAnswer","type": "text","label": "Correct Answer (not displayed)","importance": "low","default": "Correct answer","description": "Accessibility text used for readspeakers","optional": true},{"name": "feedback","type": "text","label": "Feedback text","importance": "low","default": "You got @score of @total points","description": "Feedback text, variables available: @score and @total. Example: \'You got @score of @total points.\'","optional": true},{"name": "shouldCheck","type": "text","label": "Option should have been checked","importance": "low","default": "Should have been checked","optional": true},{"name": "shouldNotCheck","type": "text","label": "Option should not have been checked","importance": "low","default": "Should not have been checked","optional": true},{"label": "Text for \"Requires answer\" message","importance": "low","name": "noInput","type": "text","default": "Please answer before viewing the solution","optional": true}]},{"name": "behaviour","type": "group","label": "Behavioural settings","importance": "low","description": "These options will let you control how the task behaves.","optional": true,"fields": [{"name": "enableRetry","type": "boolean","label": "Enable \"Retry\" button","importance": "low","default": true,"optional": true},{"name": "enableSolutionsButton","type": "boolean","label": "Enable \"Show Solution\" button","importance": "low","default": true,"optional": true},{"name": "type","type": "select","label": "Question Type","importance": "low","description": "Select the look and behaviour of the question.","default": "auto","options": [{"value": "auto","label": "Automatic"},{"value": "multi","label": "Multiple Choice (Checkboxes)"},{"value": "single","label": "Single Choice (Radio Buttons)"}]},{"name": "singlePoint","type": "boolean","label": "Give one point for the whole task","importance": "low","description": "Enable to give a total of one point for multiple correct answers. This will not be an option in \"Single answer\" mode.","default": false},{"name": "randomAnswers","type": "boolean","label": "Randomize answers","importance": "low","description": "Enable to randomize the order of questions on display.","default": true},{"label": "Require answer before the solution can be viewed","importance": "low","name": "showSolutionsRequiresInput","type": "boolean","default": true,"optional": true},{"label": "Disable image zooming for question image","importance": "low","name": "disableImageZooming","type": "boolean","default": false,"optional": true},{"label": "Show confirmation dialog on \"Check\"","importance": "low","name": "confirmCheckDialog","type": "boolean","default": false},{"label": "Show confirmation dialog on \"Retry\"","importance": "low","name": "confirmRetryDialog","type": "boolean","default": false},{"label": "Automatically check answers","importance": "low","name": "autoCheck","type": "boolean","default": false,"description": "Enabling this option will make accessibility suffer, make sure you know what you\'re doing."},{"label": "Pass percentage","name": "passPercentage","type": "number","description": "Percentage of Total score required for passing the quiz.","min": 0,"max": 100,"step": 1,"default": 100}]},{"label": "Check confirmation dialog","importance": "low","name": "confirmCheck","type": "group","common": true,"fields": [{"label": "Header text","importance": "low","name": "header","type": "text","default": "Finish ?"},{"label": "Body text","importance": "low","name": "body","type": "text","default": "Are you sure you wish to finish ?","widget": "html","enterMode": "p","tags": ["strong","em","del","u"]},{"label": "Cancel button label","importance": "low","name": "cancelLabel","type": "text","default": "Cancel"},{"label": "Confirm button label","importance": "low","name": "confirmLabel","type": "text","default": "Finish"}]},{"label": "Retry confirmation dialog","importance": "low","name": "confirmRetry","type": "group","common": true,"fields": [{"label": "Header text","importance": "low","name": "header","type": "text","default": "Retry ?"},{"label": "Body text","importance": "low","name": "body","type": "text","default": "Are you sure you wish to retry ?","widget": "html","enterMode": "p","tags": ["strong","em","del","u"]},{"label": "Cancel button label","importance": "low","name": "cancelLabel","type": "text","default": "Cancel"},{"label": "Confirm button label","importance": "low","name": "confirmLabel","type": "text","default": "Confirm"}]}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '181',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5PEditor.VerticalTabs',
                    'title' => 'H5P Editor Vertical Tabs',
                    'major_version' => '1',
                    'minor_version' => '3',
                    'patch_version' => '4',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'vertical-tabs.js',
                    'preloaded_css' => 'styles/css/vertical-tabs.css',
                    'drop_library_css' => '',
                    'semantics' => '',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '191',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.QuestionSet',
                    'title' => 'Question Set',
                    'major_version' => '1',
                    'minor_version' => '12',
                    'patch_version' => '0',
                    'runnable' => '1',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => 'iframe',
                    'preloaded_js' => 'js/questionset.js',
                    'preloaded_css' => 'css/questionset.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"name": "introPage","type": "group","label": "Quiz introduction","importance": "medium","fields": [{"name": "showIntroPage","type": "boolean","label": "Display introduction","importance": "low"},{"name": "title","type": "text","label": "Title","importance": "high","optional": true,"description": "This title will be displayed above the introduction text.","tags": ["sub","sup","strong","em"]},{"name": "introduction","type": "text","widget": "html","label": "Introduction text","importance": "medium","optional": true,"description": "This text will be displayed before the quiz starts.","enterMode": "p","tags": ["sub","sup","strong","em","p"]},{"name": "startButtonText","type": "text","label": "Start button text","importance": "low","optional": true,"default": "Start Quiz"},{"name": "backgroundImage","type": "image","label": "Background image","importance": "low","optional": true,"description": "An optional background image for the introduction."}]},{"name": "backgroundImage","type": "image","label": "Background image","importance": "low","optional": true,"description": "An optional background image for the Question set."},{"name": "progressType","type": "select","label": "Progress indicator","importance": "low","description": "Question set progress indicator style.","options": [{"value": "textual","label": "Textual"},{"value": "dots","label": "Dots"}],"default": "dots"},{"name": "passPercentage","type": "number","label": "Pass percentage","importance": "low","description": "Percentage of Total score required for passing the quiz.","min": 0,"max": 100,"step": 1,"default": 50},{"name": "questions","label": "Questions","importance": "high","type": "list","widgets": [{"name": "VerticalTabs","label": "Default"},{"name": "QuestionSetTextualEditor","label": "Textual"}],"min": 1,"entity": "question","field": {"name": "question","type": "library","label": "Question type","importance": "high","description": "Library for this question.","options": ["H5P.MultiChoice 1.9","H5P.DragQuestion 1.9","H5P.Blanks 1.7","H5P.MarkTheWords 1.6","H5P.DragText 1.5","H5P.TrueFalse 1.1"]}},{"name": "texts","type": "group","label": "Interface texts in quiz","importance": "low","common": true,"fields": [{"name": "prevButton","type": "text","label": "Back button","importance": "low","default": "Previous question"},{"name": "nextButton","type": "text","label": "Next button","importance": "low","default": "Next question"},{"name": "finishButton","type": "text","label": "Finish button","importance": "low","default": "Finish"},{"name": "textualProgress","type": "text","label": "Progress text","importance": "low","description": "Text used if textual progress is selected.","default": "Question: @current of @total questions","tags": ["strong","em"]},{"name": "jumpToQuestion","type": "text","label": "Label for jumping to a certain question","importance": "low","description": "You must use the placeholder \' % d\' instead of the question number, and %total instead of total amount of questions.","default": "Question %d of %total"},{"name": "questionLabel","type": "text","label": "Copyright dialog question label","importance": "low","default": "Question"},{"name": "readSpeakerProgress","type": "text","label": "Readspeaker progress","importance": "low","description": "May use @current and @total question variables","default": "Question @current of @total"},{"name": "unansweredText","type": "text","label": "Unanswered question text","importance": "low","default": "Unanswered"},{"name": "answeredText","type": "text","label": "Answered question text","importance": "low","default": "Answered"},{"name": "currentQuestionText","type": "text","label": "Current question text","importance": "low","default": "Current question"}]},{"name": "disableBackwardsNavigation","type": "boolean","label": "Disable backwards navigation","importance": "low","description": "This option will only allow you to move forward in Question Set","optional": true,"default": false},{"name": "randomQuestions","type": "boolean","label": "Randomize questions","importance": "low","description": "Enable to randomize the order of questions on display.","default": false},{"name": "poolSize","type": "number","min": 1,"label": "Number of questions to be shown:","importance": "low","description": "Create a randomized batch of questions from the total.","optional": true},{"name": "endGame","type": "group","label": "Quiz finished","importance": "medium","fields": [{"name": "showResultPage","type": "boolean","label": "Display results","importance": "low","default": true},{"name": "noResultMessage","type": "text","label": "No results message","importance": "low","description": "Text displayed on end page when \\"Display results\\" is disabled","default": "Finished","optional": true},{"name": "message","type": "text","label": "Feedback heading","importance": "low","default": "Your result:","optional": true,"description": "This heading will be displayed at the end of the quiz when the user has answered all questions.","tags": ["strong","em"]},{"name": "scoreString","type": "text","label": "Score display text","importance": "low","description": "Text used to display Total user score. \\"@score\\" will be replaced by calculated score, \\"@total\\" will be replaced by maximum possible score. ","default": "You got @score of @total points","optional": true},{"name": "successGreeting","type": "text","label": "Quiz passed greeting","importance": "low","placeholder": "Congratulations!","default": "Congratulations!","optional": true,"description": "This text will be displayed above the score if the user has successfully passed the quiz.","tags": ["strong","em"]},{"name": "successComment","type": "text","widget": "html","label": "Passed comment","importance": "low","default": "You did very well!","optional": true,"description": "This comment will be displayed after the score if the user has successfully passed the quiz.","tags": ["sub","sup","strong","em","a","p"]},{"name": "failGreeting","type": "text","label": "Quiz failed title","importance": "low","default": "You did not pass this time.","optional": true,"description": "This text will be displayed above the score if the user has failed the quiz.","tags": ["strong","em"]},{"name": "failComment","type": "text","widget": "html","label": "Failed comment","importance": "low","default": "Have another try!","optional": true,"description": "This comment will be displayed after the score if the user has failed the quiz.","tags": ["sub","sup","strong","em","a","p"]},{"name": "solutionButtonText","type": "text","label": "Solution button label","importance": "low","default": "Show solution","description": "Text for the solution button."},{"name": "retryButtonText","type": "text","label": "Retry button label","importance": "low","default": "Retry","description": "Text for the retry button."},{"name": "finishButtonText","type": "text","label": "Finish button text","importance": "low","default": "Finish"},{"name": "showAnimations","type": "boolean","label": "Display video before quiz results","importance": "low"},{"name": "skippable","type": "boolean","label": "Enable skip video button","importance": "low"},{"name": "skipButtonText","type": "text","label": "Skip video button label","importance": "low","default": "Skip video"},{"name": "successVideo","type": "video","label": "Passed video","importance": "low","optional": true,"description": "This video will be played if the user successfully passed the quiz."},{"name": "failVideo","type": "video","label": "Fail video","importance": "low","optional": true,"description": "This video will be played if the user failes the quiz."}]},{"name": "override","type": "group","label": "Settings for \\"Show solution\\" and \\"Retry\\" buttons","importance": "low","optional": true,"fields": [{"name": "showSolutionButton","type": "select","label": "Override \\"Show Solution\\" button","importance": "low","description": "This option determines if the \\"Show Solution\\" button will be shown for all questions, disabled for all or configured for each question individually.","optional": true,"options": [{"value": "on","label": "Enabled"},{"value": "off","label": "Disabled"}]},{"name": "retryButton","type": "select","label": "Override \\"Retry\\" button","importance": "low","description": "This option determines if the \\"Retry\\" button will be shown for all questions, disabled for all or configured for each question individually.","optional": true,"options": [{"value": "on","label": "Enabled"},{"value": "off","label": "Disabled"}]}]}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '192',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.Flashcards',
                    'title' => 'Flashcards',
                    'major_version' => '1',
                    'minor_version' => '1',
                    'patch_version' => '3',
                    'runnable' => '1',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'js/flashcards.js',
                    'preloaded_css' => 'css/flashcards.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"name": "description","type": "text","label": "Task description"},{"name": "cards","type": "list","widgets": [{"name": "VerticalTabs","label": "Default"}],"label": "Cards","entity": "card","min": 1,"defaultNum": 1,"field": {"name": "card","type": "group","label": "Card","fields": [{"name": "text","type": "text","label": "Question","optional": true,"description": "Optional textual question for the card. (The card may use just an image, just a text or both)"},{"name": "answer","type": "text","label": "Answer","optional": true,"description": "Optional answer(solution) for the card."},{"name": "image","type": "image","label": "Image","optional": true,"description": "Optional image for the card. (The card may use just an image, just a text or both)"},{"name": "tip","type": "group","label": "Tip","optional": true,"fields": [{"name": "tip","label": "Tip text","type": "text","optional": true}]}]}},{"label": "Progress text","name": "progressText","type": "text","default": "Card @card of @total","description": "Progress text, variables available: @card and @total. Example: \'Card @card of @total\'","common": true},{"label": "Text for the next button","name": "next","type": "text","default": "Next","common": true},{"label": "Text for the previous button","name": "previous","type": "text","default": "Previous","common": true},{"label": "Text for the check answers button","name": "checkAnswerText","type": "text","default": "Check","common": true},{"label": "Require user input before the solution can be viewed","name": "showSolutionsRequiresInput","type": "boolean","default": true,"optional": true}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '199',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.DragQuestion',
                    'title' => 'Drag and Drop',
                    'major_version' => '1',
                    'minor_version' => '11',
                    'patch_version' => '2',
                    'runnable' => '1',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => 'iframe',
                    'preloaded_js' => 'h5p-drag-question.js',
                    'preloaded_css' => 'css/dragquestion.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"name": "scoreShow","type": "text","label": "Check answer button","importance": "low","default": "Check","common": true},{"name": "tryAgain","type": "text","label": "Retry button","importance": "low","default": "Retry","common": true,"optional": true},{"label": "Score explanation text","importance": "low","name": "scoreExplanation","type": "text","default": "Correct answers give +1 point. Incorrect answers give -1 point. The lowest possible score is 0.","common": true,"optional": true},{"name": "question","importance": "high","type": "group","widget": "wizard","fields": [{"name": "settings","type": "group","label": "Settings","importance": "high","fields": [{"name": "questionTitle","type": "text","label": "The title of this question","importance": "high","default": "Drag and Drop","description": "Used in summaries, statistics etc."},{"name": "showTitle","type": "boolean","label": "Show Title","importance": "low","description": "Uncheck this option if you do not want this title to be displayed. The title will only be displayed in summaries, statistics etc.","default": true},{"name": "background","type": "image","label": "Background image","importance": "low","optional": true,"description": "Optional. Select an image to use as background for your drag and drop task."},{"name": "size","type": "group","widget": "dimensions","label": "Task size","importance": "low","description": "Specify how large (in px) the play area should be.","default": {"width": 620,"height": 310,"field": "background"},"fields": [{"name": "width","type": "number"},{"name": "height","type": "number"}]}]},{"name": "task","type": "group","widget": "dragQuestion","label": "Task","importance": "high","description": "Start by placing your drop zones.<br/>Next, place your droppable elements and check off the appropriate drop zones.<br/>Last, edit your drop zone again and check off the correct answers.","fields": [{"name": "elements","type": "list","label": "Elements","importance": "high","entity": "element","field": {"type": "group","label": "Element","importance": "high","fields": [{"name": "type","type": "library","description": "Choose the type of content you would like to add.","importance": "medium","options": ["H5P.AdvancedText 1.1","H5P.Image 1.0"]},{"name": "x","type": "number","widget": "none"},{"name": "y","type": "number","widget": "none"},{"name": "height","type": "number","widget": "none"},{"name": "width","type": "number","widget": "none"},{"name": "dropZones","type": "select","widget": "dynamicCheckboxes","label": "Select drop zones","importance": "high","multiple": true},{"name": "backgroundOpacity","type": "number","label": "Background Opacity","importance": "low","min": 0,"max": 100,"step": 5,"default": 100,"optional": true},{"name": "multiple","type": "boolean","label": "Infinite number of element instances","importance": "low","description": "Clones this element so that it can be dragged to multiple drop zones.","default": false}]}},{"name": "dropZones","type": "list","label": "Drop Zones","importance": "high","entity": "Drop Zone","field": {"type": "group","label": "Drop Zone","importance": "high","fields": [{"name": "label","type": "text","widget": "html","label": "Label","importance": "medium","enterMode": "div","tags": ["strong","em","del"]},{"name": "showLabel","type": "boolean","label": "Show label","importance": "low"},{"name": "x","type": "number","widget": "none"},{"name": "y","type": "number","widget": "none"},{"name": "height","type": "number","widget": "none"},{"name": "width","type": "number","widget": "none"},{"name": "correctElements","type": "select","widget": "dynamicCheckboxes","label": "Select correct elements","importance": "low","multiple": true},{"name": "backgroundOpacity","type": "number","label": "Background Opacity","importance": "low","min": 0,"max": 100,"step": 5,"default": 100,"optional": true},{"name": "tipsAndFeedback","type": "group","label": "Tips and feedback","importance": "low","optional": true,"fields": [{"name": "tip","label": "Tip text","importance": "low","type": "text","widget": "html","tags": ["p","br","strong","em"],"optional": true},{"name": "feedbackOnCorrect","type": "text","label": "Message displayed on correct match","importance": "low","description": "Message will appear below the task on \\"check\\" if correct droppable is matched.","optional": true},{"name": "feedbackOnIncorrect","type": "text","label": "Message displayed on incorrect match","importance": "low","description": "Message will appear below the task on \\"check\\" if the match is incorrect.","optional": true}]},{"name": "single","type": "boolean","label": "This drop zone can only contain one element","description": "Make sure there is only one correct answer for this dropzone","importance": "low","default": false},{"name": "autoAlign","type": "boolean","label": "Enable Auto-Align","importance": "low","description": "Will auto-align all draggables dropped in this zone."}]}}]}]},{"name": "overallFeedback","type": "group","label": "Overall Feedback","importance": "low","expanded": true,"fields": [{"name": "overallFeedback","type": "list","widgets": [{"name": "RangeList","label": "Default"}],"importance": "high","label": "Define custom feedback for any score range","description": "Click the \\"Add range\\" button to add as many ranges as you need. Example: 0-20% Bad score, 21-91% Average Score, 91-100% Great Score!","entity": "range","min": 1,"defaultNum": 1,"optional": true,"field": {"name": "overallFeedback","type": "group","importance": "low","fields": [{"name": "from","type": "number","label": "Score Range","min": 0,"max": 100,"default": 0,"unit": "%"},{"name": "to","type": "number","min": 0,"max": 100,"default": 100,"unit": "%"},{"name": "feedback","type": "text","label": "Feedback for defined score range","importance": "low","placeholder": "Fill in the feedback","optional": true}]}}]},{"name": "behaviour","type": "group","label": "Behavioural settings","importance": "low","description": "These options will let you control how the task behaves.","optional": true,"fields": [{"name": "enableRetry","type": "boolean","label": "Enable \\"Retry\\"","importance": "low","default": true},{"label": "Require user input before the solution can be viewed","importance": "low","name": "showSolutionsRequiresInput","type": "boolean","default": true},{"name": "singlePoint","type": "boolean","label": "Give one point for the whole task","importance": "low","description": "Disable to give one point for each draggable that is placed correctly.","default": false},{"label": "Apply penalties","name": "applyPenalties","type": "boolean","description": "Apply penalties for elements dropped in the wrong drop zones. This must be enabled when the same element(s) are able to be dropped into multiple drop zones, or if there is only one drop-zone. If this is not enabled, learners may match all items to all drop-zones and always receive a full score.","default": true},{"name": "enableScoreExplanation","type": "boolean","label": "Enable score explanation","description": "Display a score explanation to user when checking their answers (if the \'Apply penalties\' option has been selected).","importance": "low","default": true,"optional": true,"widget": "showWhen","showWhen": {"rules": [{"field": "singlePoint","equals": false}]}},{"name": "backgroundOpacity","type": "text","label": "Background opacity for draggables","importance": "low","description": "If this field is set, it will override opacity set on all draggable elements. This should be a number between 0 and 100, where 0 means full transparency and 100 means no transparency","optional": true},{"name": "dropZoneHighlighting","type": "select","label": "Drop Zone Highlighting","importance": "low","description": "Choose when to highlight drop zones.","default": "dragging","options": [{"value": "dragging","label": "When dragging"},{"value": "always","label": "Always"},{"value": "never","label": "Never"}]},{"name": "autoAlignSpacing","type": "number","label": "Spacing for Auto-Align (in px)","importance": "low","min": 0,"default": 2,"optional": true},{"name": "enableFullScreen","label": "Enable FullScreen","importance": "low","type": "boolean","description": "Check this option to enable the full screen button.","default": false},{"name": "showScorePoints","type": "boolean","label": "Show score points","description": "Show points earned for each answer. Not available when the \'Give one point for the whole task\' option is enabled.","importance": "low","default": true}]},{"name": "localize","type": "group","label": "Localize","common": true,"fields": [{"name": "fullscreen","type": "text","label": "Fullscreen label","default": "Fullscreen"},{"name": "exitFullscreen","type": "text","label": "Exit fullscreen label","default": "Exit fullscreen"}]},{"name": "grabbablePrefix","type": "text","label": "Grabbable prefix","importance": "low","default": "Grabbable {num} of {total}.","common": true},{"name": "grabbableSuffix","type": "text","label": "Grabbable suffix","importance": "low","default": "Placed in dropzone {num}.","common": true},{"name": "dropzonePrefix","type": "text","label": "Dropzone prefix","importance": "low","default": "Dropzone {num} of {total}.","common": true},{"name": "noDropzone","type": "text","label": "No dropzone selection label","importance": "low","default": "No dropzone.","common": true},{"name": "tipLabel","type": "text","label": "Label for show tip button","importance": "low","default": "Show tip.","common": true},{"name": "tipAvailable","type": "text","label": "Label for tip available","importance": "low","default": "Tip available","common": true},{"name": "correctAnswer","type": "text","label": "Label for correct answer","importance": "low","default": "Correct answer","common": true},{"name": "wrongAnswer","type": "text","label": "Label for incorrect answer","importance": "low","default": "Wrong answer","common": true},{"name": "feedbackHeader","type": "text","label": "Header for panel containing feedback for correct/incorrect answers","importance": "low","default": "Feedback","common": true}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '202',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.InteractiveVideo',
                    'title' => 'Interactive Video',
                    'major_version' => '1',
                    'minor_version' => '17',
                    'patch_version' => '2',
                    'runnable' => '1',
                    'restricted' => '0',
                    'fullscreen' => '1',
                    'embed_types' => 'iframe',
                    'preloaded_js' => 'dist/h5p-interactive-video.js',
                    'preloaded_css' => 'dist/h5p-interactive-video.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"name": "interactiveVideo","type": "group","widget": "wizard","label": "Interactive Video Editor","importance": "high","fields": [{"name": "video","type": "group","label": "Upload/embed video","importance": "high","fields": [{"name": "files","type": "video","label": "Add a video","importance": "high","description": "Click below to add a video you wish to use in your interactive video. You can add a video link or upload video files. It is possible to add several versions of the video with different qualities. To ensure maximum support in browsers at least add a version in webm and mp4 formats.","extraAttributes": ["metadata"],"enableCustomQualityLabel": true},{"name": "startScreenOptions","type": "group","label": "Start screen options (unsupported for YouTube videos)","importance": "low","fields": [{"name": "title","type": "text","label": "The title of this interactive video","importance": "low","maxLength": 60,"default": "Interactive Video","description": "Used in summaries, statistics etc."},{"name": "hideStartTitle","type": "boolean","label": "Hide title on video start screen","importance": "low","optional": true,"default": false},{"name": "shortStartDescription","type": "text","label": "Short description (Optional)","importance": "low","optional": true,"maxLength": 120,"description": "Optional. Display a short description text on the video start screen. Does not work for YouTube videos."},{"name": "poster","type": "image","label": "Poster image","importance": "low","optional": true,"description": "Image displayed before the user launches the video. Does not work for YouTube Videos."},{"name": "copyright","type": "text","widget": "html","enterMode": "p","label": "Video copyright information","importance": "low","optional": true,"description": "Information regarding copyright of the video and elements used in the video.","tags": ["strong","em","del","a"]}]},{"name": "textTracks","type": "group","label": "Text tracks (unsupported for YouTube videos)","importance": "low","fields": [{"name": "videoTrack","type": "list","label": "Available text tracks","importance": "low","optional": true,"entity": "Track","min": 0,"defaultNum": 1,"field": {"name": "track","type": "group","label": "Track","importance": "low","expanded": false,"fields": [{"name": "label","type": "text","label": "Track label","description": "Used if you offer multiple tracks and the user has to choose a track. For instance \'Spanish subtitles\' could be the label of a Spanish subtitle track.","importance": "low","default": "Subtitles","optional": true},{"name": "kind","type": "select","label": "Type of text track","importance": "low","default": "subtitles","options": [{"value": "subtitles","label": "Subtitles"},{"value": "captions","label": "Captions"},{"value": "descriptions","label": "Descriptions"}]},{"name": "srcLang","type": "text","label": "Source language, must be defined for subtitles","importance": "low","default": "en","description": "Must be a valid BCP 47 language tag. If \'Subtitles\' is the type of text track selected, the source language of the track must be defined."},{"name": "track","type": "file","label": "Track source (WebVTT file)","importance": "low"}]}}]}]},{"name": "assets","type": "group","label": "Add interactions","importance": "high","widget": "interactiveVideo","video": "video/files","poster": "video/startScreenOptions/poster","fields": [{"name": "interactions","type": "list","field": {"name": "interaction","type": "group","fields": [{"name": "duration","type": "group","widget": "duration","label": "Display time","importance": "low","fields": [{"name": "from","type": "number"},{"name": "to","type": "number"}]},{"name": "pause","label": "Pause video","importance": "low","type": "boolean"},{"name": "displayType","label": "Display as","importance": "low","description": "<b>Button</b> is a collapsed interaction the user must press to open. <b>Poster</b> is an expanded interaction displayed directly on top of the video","type": "select","widget": "imageRadioButtonGroup","options": [{"value": "button","label": "Button"},{"value": "poster","label": "Poster"}],"default": "button"},{"name": "buttonOnMobile","label": "Turn into button on small screens","importance": "low","type": "boolean","default": false},{"name": "label","type": "text","widget": "html","label": "Label","importance": "low","description": "Label displayed next to interaction icon.","optional": true,"enterMode": "p","tags": ["p"]},{"name": "x","type": "number","importance": "low","widget": "none"},{"name": "y","type": "number","importance": "low","widget": "none"},{"name": "width","type": "number","widget": "none","importance": "low","optional": true},{"name": "height","type": "number","widget": "none","importance": "low","optional": true},{"name": "libraryTitle","type": "text","importance": "low","optional": true,"widget": "none"},{"name": "action","type": "library","importance": "low","options": ["H5P.Nil 1.0","H5P.Text 1.1","H5P.Table 1.1","H5P.Link 1.3","H5P.Image 1.0","H5P.Summary 1.8","H5P.SingleChoiceSet 1.9","H5P.MultiChoice 1.10","H5P.TrueFalse 1.2","H5P.Blanks 1.8","H5P.DragQuestion 1.11","H5P.MarkTheWords 1.7","H5P.DragText 1.6","H5P.GoToQuestion 1.3","H5P.IVHotspot 1.2","H5P.Questionnaire 1.2"]},{"name": "adaptivity","type": "group","label": "Adaptivity","importance": "low","optional": true,"fields": [{"name": "correct","type": "group","label": "Action on all correct","fields": [{"name": "seekTo","type": "number","widget": "timecode","label": "Seek to","description": "Enter timecode in the format M:SS"},{"name": "allowOptOut","type": "boolean","label": "Allow the user to opt out and continue"},{"name": "message","type": "text","widget": "html","enterMode": "p","tags": ["strong","em","del","a"],"label": "Message"},{"name": "seekLabel","type": "text","label": "Label for seek button"}]},{"name": "wrong","type": "group","label": "Action on wrong","fields": [{"name": "seekTo","type": "number","widget": "timecode","label": "Seek to","description": "Enter timecode in the format M:SS"},{"name": "allowOptOut","type": "boolean","label": "Allow the user to opt out and continue"},{"name": "message","type": "text","widget": "html","enterMode": "p","tags": ["strong","em","del","a"],"label": "Message"},{"name": "seekLabel","type": "text","label": "Label for seek button"}]},{"name": "requireCompletion","type": "boolean","label": "Require full score for task before proceeding","description": "For best functionality this option should be used in conjunction with the \\"Prevent skipping forward in a video\\" option of Interactive Video."}]},{"name": "visuals","label": "Visuals","importance": "low","type": "group","fields": [{"name": "backgroundColor","type": "text","label": "Background color","widget": "colorSelector","default": "rgb(255, 255, 255)","spectrum": {"showInput": true,"showAlpha": true,"preferredFormat": "rgb","showPalette": true,"palette": [["rgba(0, 0, 0, 0)"],["rgb(67, 67, 67)","rgb(102, 102, 102)","rgb(204, 204, 204)","rgb(217, 217, 217)","rgb(255, 255, 255)"],["rgb(152, 0, 0)","rgb(255, 0, 0)","rgb(255, 153, 0)","rgb(255, 255, 0)","rgb(0, 255, 0)","rgb(0, 255, 255)","rgb(74, 134, 232)","rgb(0, 0, 255)","rgb(153, 0, 255)","rgb(255, 0, 255)"],["rgb(230, 184, 175)","rgb(244, 204, 204)","rgb(252, 229, 205)","rgb(255, 242, 204)","rgb(217, 234, 211)","rgb(208, 224, 227)","rgb(201, 218, 248)","rgb(207, 226, 243)","rgb(217, 210, 233)","rgb(234, 209, 220)","rgb(221, 126, 107)","rgb(234, 153, 153)","rgb(249, 203, 156)","rgb(255, 229, 153)","rgb(182, 215, 168)","rgb(162, 196, 201)","rgb(164, 194, 244)","rgb(159, 197, 232)","rgb(180, 167, 214)","rgb(213, 166, 189)","rgb(204, 65, 37)","rgb(224, 102, 102)","rgb(246, 178, 107)","rgb(255, 217, 102)","rgb(147, 196, 125)","rgb(118, 165, 175)","rgb(109, 158, 235)","rgb(111, 168, 220)","rgb(142, 124, 195)","rgb(194, 123, 160)","rgb(166, 28, 0)","rgb(204, 0, 0)","rgb(230, 145, 56)","rgb(241, 194, 50)","rgb(106, 168, 79)","rgb(69, 129, 142)","rgb(60, 120, 216)","rgb(61, 133, 198)","rgb(103, 78, 167)","rgb(166, 77, 121)","rgb(91, 15, 0)","rgb(102, 0, 0)","rgb(120, 63, 4)","rgb(127, 96, 0)","rgb(39, 78, 19)","rgb(12, 52, 61)","rgb(28, 69, 135)","rgb(7, 55, 99)","rgb(32, 18, 77)","rgb(76, 17, 48)"]]}},{"name": "boxShadow","type": "boolean","label": "Box shadow","default": true,"description": "Adds a subtle shadow around the interaction. You might want to disable this for completely transparent interactions"}]},{"name": "goto","label": "Go to on click","importance": "low","type": "group","fields": [{"name": "type","label": "Type","type": "select","widget": "selectToggleFields","options": [{"value": "timecode","label": "Timecode","hideFields": ["url"]},{"value": "url","label": "Another page (URL)","hideFields": ["time"]}],"optional": true},{"name": "time","type": "number","widget": "timecode","label": "Go To","description": "The target time the user will be taken to upon pressing the hotspot. Enter timecode in the format M:SS.","optional": true},{"name": "url","type": "group","label": "URL","widget": "linkWidget","optional": true,"fields": [{"name": "protocol","type": "select","label": "Protocol","options": [{"value": "http://","label": "http://"},{"value": "https://","label": "https://"},{"value": "/","label": "(root relative)"},{"value": "other","label": "other"}],"optional": true,"default": "http://"},{"name": "url","type": "text","label": "URL","optional": true}]},{"name": "visualize","type": "boolean","label": "Visualize","description": "Show that interaction can be clicked by adding a border and an icon"}]}]}},{"name": "bookmarks","importance": "low","type": "list","field": {"name": "bookmark","type": "group","fields": [{"name": "time","type": "number"},{"name": "label","type": "text"}]}}]},{"name": "summary","type": "group","label": "Summary task","importance": "high","fields": [{"name": "task","type": "library","options": ["H5P.Summary 1.8"],"default": {"library": "H5P.Summary 1.8","params": {}}},{"name": "displayAt","type": "number","label": "Display at","description": "Number of seconds before the video ends.","default": 3}]}]},{"name": "override","type": "group","label": "Behavioural settings","importance": "low","optional": true,"fields": [{"name": "startVideoAt","type": "number","widget": "timecode","label": "Start video at","importance": "low","optional": true,"description": "Enter timecode in the format M:SS"},{"name": "autoplay","type": "boolean","label": "Auto-play video","default": false,"optional": true,"description": "Start playing the video automatically"},{"name": "loop","type": "boolean","label": "Loop the video","default": false,"optional": true,"description": "Check if video should run in a loop"},{"name": "showSolutionButton","type": "select","label": "Override \\"Show Solution\\" button","importance": "low","description": "This option determines if the \\"Show Solution\\" button will be shown for all questions, disabled for all or configured for each question individually.","optional": true,"options": [{"value": "on","label": "Enabled"},{"value": "off","label": "Disabled"}]},{"name": "retryButton","type": "select","label": "Override \\"Retry\\" button","importance": "low","description": "This option determines if the \\"Retry\\" button will be shown for all questions, disabled for all or configured for each question individually.","optional": true,"options": [{"value": "on","label": "Enabled"},{"value": "off","label": "Disabled"}]},{"name": "showBookmarksmenuOnLoad","type": "boolean","label": "Start with bookmarks menu open","importance": "low","default": false,"description": "This function is not available on iPad when using YouTube as video source."},{"name": "showRewind10","type": "boolean","label": "Show button for rewinding 10 seconds","importance": "low","default": false},{"name": "preventSkipping","type": "boolean","default": false,"label": "Prevent skipping forward in a video","importance": "low","description": "Enabling this options will disable user video navigation through default controls."},{"name": "deactivateSound","type": "boolean","default": false,"label": "Deactivate sound","importance": "low","description": "Enabling this option will deactivate the video\'s sound and prevent it from being switched on . "}]},{"name": "l10n","type": "group","label": "Localize","importance": "low","common": true,"optional": true,"fields": [{"name": "interaction","type": "text","label": "Interaction title","importance": "low","default": "Interaction","optional": true},{"name": "play","type": "text","label": "Play title","importance": "low","default": "Play","optional": true},{"name": "pause","type": "text","label": "Pause title","importance": "low","default": "Pause","optional": true},{"name": "mute","type": "text","label": "Mute title","importance": "low","default": "Mute","optional": true},{"name": "unmute","type": "text","label": "Unmute title","importance": "low","default": "Unmute","optional": true},{"name": "quality","type": "text","label": "Video quality title","importance": "low","default": "Video Quality","optional": true},{"name": "captions","type": "text","label": "Video captions title","importance": "low","default": "Captions","optional": true},{"name": "close","type": "text","label": "Close button text","importance": "low","default": "Close","optional": true},{"name": "fullscreen","type": "text","label": "Fullscreen title","importance": "low","default": "Fullscreen","optional": true},{"name": "exitFullscreen","type": "text","label": "Exit fullscreen title","importance": "low","default": "Exit Fullscreen","optional": true},{"name": "summary","type": "text","label": "Summary title","importance": "low","default": "Summary","optional": true},{"name": "bookmarks","type": "text","label": "Bookmarks title","importance": "low","default": "Bookmarks","optional": true},{"name": "defaultAdaptivitySeekLabel","type": "text","label": "Default label for adaptivity seek button","importance": "low","default": "Continue","optional": true},{"name": "continueWithVideo","type": "text","label": "Default label for continue video button","importance": "low","default": "Continue with video","optional": true},{"name": "playbackRate","type": "text","label": "Set playback rate","importance": "low","default": "Playback Rate","optional": true},{"name": "rewind10","type": "text","label": "Rewind 10 Seconds","importance": "low","default": "Rewind 10 Seconds","optional": true},{"name": "navDisabled","type": "text","label": "Navigation is disabled text","importance": "low","default": "Navigation is disabled","optional": true},{"name": "sndDisabled","type": "text","label": "Sound is disabled text","importance": "low","default": "Sound is disabled","optional": true},{"name": "requiresCompletionWarning","type": "text","label": "Warning that the user must answer the question correctly before continuing","importance": "low","default": "You need to answer all the questions correctly before continuing . ","optional": true},{"name": "back","type": "text","label": "Back button","importance": "low","default": "Back","optional": true},{"name": "hours","type": "text","label": "Passed time hours","importance": "low","default": "Hours","optional": true},{"name": "minutes","type": "text","label": "Passed time minutes","importance": "low","default": "Minutes","optional": true},{"name": "seconds","type": "text","label": "Passed time seconds","importance": "low","default": "Seconds","optional": true},{"name": "currentTime","type": "text","label": "Label for current time","importance": "low","default": "Current time:","optional": true},{"name": "totalTime","type": "text","label": "Label for total time","importance": "low","default": "Total time:","optional": true},{"name": "navigationHotkeyInstructions","type": "text","label": "Text for explaining navigation hotkey","importance": "low","default": "Use key k for starting and stopping video at any time","optional": true},{"name": "singleInteractionAnnouncement","type": "text","label": "Text explaining that a single interaction with a name has come into view","importance": "low","default": "Interaction appeared:","optional": true},{"name": "multipleInteractionsAnnouncement","type": "text","label": "Text for explaining that multiple interactions have come into view","importance": "low","default": "Multiple interactions appeared . ","optional": true},{"name": "videoPausedAnnouncement","type": "text","label": "Video is paused announcement","importance": "low","default": "Video is paused","optional": true}]}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '207',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.Questionnaire',
                    'title' => 'Questionnaire',
                    'major_version' => '1',
                    'minor_version' => '2',
                    'patch_version' => '2',
                    'runnable' => '1',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => 'iframe',
                    'preloaded_js' => 'dist/dist.js',
                    'preloaded_css' => 'dist/styles.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"name": "questionnaireElements","label": "Questionnaire elements","importance": "high","type": "list","widgets": [{"name": "VerticalTabs","label": "Default","importance": "high"}],"entity": "element","min": 1,"defaultNum": 1,"field": {"name": "libraryGroup","label": "Choose library","importance": "high","type": "group","fields": [{"name": "library","type": "library","label": "Library","importance": "high","description": "Choose a library","options": ["H5P.OpenEndedQuestion 1.0","H5P.SimpleMultiChoice 1.1"]},{"name": "requiredField","type": "boolean","label": "Required field","importance": "low","default": false}]}},{"name": "successScreenOptions","label": "Success screen options","importance": "low","type": "group","fields": [{"name": "enableSuccessScreen","label": "Enable success screen","importance": "low","type": "boolean","default": true},{"name": "successScreenImage","label": "Add success screen image","importance": "low","type": "group","fields": [{"name": "successScreenImage","label": "Replace success icon with image","importance": "low","type": "library","optional": true,"options": ["H5P.Image 1.0"]}]},{"name": "successMessage","type": "text","label": "Text to display on submit","importance": "low","default": "You have completed the questionnaire."}]},{"name": "uiElements","label": "UI Elements","importance": "low","type": "group","fields": [{"name": "buttonLabels","type": "group","label": "Button labels","importance": "low","fields": [{"name": "prevLabel","type": "text","label": "Previous button label","importance": "low","default": "Back"},{"name": "continueLabel","type": "text","label": "Continue button label","importance": "low","default": "Continue"},{"name": "nextLabel","type": "text","label": "Next button label","importance": "low","default": "Next"},{"name": "submitLabel","type": "text","label": "Submit button label","importance": "low","default": "Submit"}]},{"name": "accessibility","type": "group","label": "Accessibility","importance": "low","fields": [{"name": "requiredTextExitLabel","type": "text","label": "Required message exit button label","importance": "low","default": "Close error message"},{"name": "progressBarText","type": "text","label": "Progress bar text","importance": "low","default": "Question %current of %max","description": "Used to tell assistive technologies what question it is. Variables: [ %current, %max ]"}]},{"name": "requiredMessage","type": "text","label": "Required message","importance": "low","default": "This question requires an answer","description": "Will display if this field is unanswered and required by a wrapper content type"},{"name": "requiredText","type": "text","label": "Required symbol text","importance": "low","default": "required","description": "Text that will accompany an asterisk to signal that a question is required"},{"name": "submitScreenTitle","type": "text","label": "Title for the submit screen","importance": "low","default": "You successfully answered all of the questions"},{"name": "submitScreenSubtitle","type": "text","label": "Subtitle for the submit screen","importance": "low","default": "Click below to submit your answers"}]}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '208',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.OpenEndedQuestion',
                    'title' => 'Open Ended Question',
                    'major_version' => '1',
                    'minor_version' => '0',
                    'patch_version' => '6',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'dist/dist.js',
                    'preloaded_css' => 'dist/styles.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"name": "question","label": "Question or description","importance": "high","type": "text"},{"name": "placeholderText","label": "Placeholder text","default": "Start writing...","importance": "low","description": "Text that initially will be shown in the input field. Will be removed automatically when the user starts writing.","type": "text","optional": true},{"name": "inputRows","label": "Input rows","type": "select","importance": "high","description": "Determines the height of the input field.","options": [{"value": "1","label": "1 line"},{"value": "2","label": "2 lines"},{"value": "3","label": "3 lines"},{"value": "10","label": "10 lines"}],"default": "1"}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '209',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.SimpleMultiChoice',
                    'title' => 'Simple Multi Choice',
                    'major_version' => '1',
                    'minor_version' => '1',
                    'patch_version' => '2',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'dist/dist.js',
                    'preloaded_css' => 'dist/styles.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"name": "question","label": "Question","importance": "high","type": "text"},{"name": "inputType","label": "Multiple choice type","importance": "high","type": "select","options": [{"label": "Multiple answers","value": "checkbox"},{"label": "Single answer","value": "radio"}],"default": "checkbox"},{"name": "alternatives","label": "Answer alternatives","type": "list","importance": "high","entity": "Alternative","min": 2,"field": {"type": "group","name": "alternative","label": "Alternative","fields": [{"name": "text","label": "Text","importance": "high","type": "text"},{"name": "feedback","type": "group","label": "Feedback","importance": "low","optional": true,"fields": [{"name": "chosenFeedback","type": "text","widget": "html","label": "Message displayed if answer is selected","importance": "low","description": "Message will appear below the answer on \"continue\" if this answer is selected.","optional": true,"tags": ["strong","em","sub","sup","a"]},{"name": "notChosenFeedback","type": "text","widget": "html","label": "Message displayed if answer is not selected","importance": "low","description": "Message will appear below the answer on \"continue\" if this answer is not selected.","optional": true,"tags": ["strong","em","sub","sup","a"]}]}]}}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '214',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5PEditor.InteractiveVideo',
                    'title' => 'Interactive Video Editor',
                    'major_version' => '1',
                    'minor_version' => '17',
                    'patch_version' => '2',
                    'runnable' => '0',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => '',
                    'preloaded_js' => 'Scripts/image-radio-button-group.js, Scripts/interactive-video-editor.js, Scripts/guided-tours.js, Scripts/require-completion.js',
                    'preloaded_css' => 'styles/image-radio-button-group.css, styles/interactive-video-editor.css, styles/require-completion.css',
                    'drop_library_css' => '',
                    'semantics' => '',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => '284',
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.Blanks',
                    'title' => 'Fill in the Blanks',
                    'major_version' => '1',
                    'minor_version' => '11',
                    'patch_version' => '3',
                    'runnable' => '1',
                    'restricted' => '0',
                    'fullscreen' => '0',
                    'embed_types' => 'iframe',
                    'preloaded_js' => 'js/blanks.js, js/cloze.js',
                    'preloaded_css' => 'css/blanks.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"name": "media","type": "group","label": "Media","importance": "medium","fields": [{"name": "type","type": "library","label": "Type","options": ["H5P.Image 1.1","H5P.Video 1.5"],"optional": true,"description": "Optional media to display above the question."}]},{"label": "Task description","importance": "high","name": "text","type": "text","widget": "html","default": "Fill in the missing words","description": "A guide telling the user how to answer this task.","enterMode": "p","tags": ["strong","em","u","a","ul","ol","h2","h3","hr"]},{"name": "questions","type": "list","label": "Text blocks","importance": "high","entity": "text block","min": 1,"max": 31,"field": {"name": "question","type": "text","widget": "html","label": "Line of text","importance": "high","placeholder": "Oslo is the capital of *Norway*.","description": "","important": {"description": "<ul><li>Blanks are added with an asterisk (*) in front and behind the correct word/phrase.</li><li>Alternative answers are separated with a forward slash (/).</li><li>You may add a textual tip, using a colon (:) in front of the tip.</li></ul>","example": "H5P content may be edited using a *browser/web-browser:Something you use every day*."},"enterMode": "p","tags": ["strong","em","del","u"]}},{"name": "overallFeedback","type": "group","label": "Overall Feedback","importance": "low","expanded": true,"fields": [{"name": "overallFeedback","type": "list","widgets": [{"name": "RangeList","label": "Default"}],"importance": "high","label": "Define custom feedback for any score range","description": "Click the \"Add range\" button to add as many ranges as you need. Example: 0-20% Bad score, 21-91% Average Score, 91-100% Great Score!","entity": "range","min": 1,"defaultNum": 1,"optional": true,"field": {"name": "overallFeedback","type": "group","importance": "low","fields": [{"name": "from","type": "number","label": "Score Range","min": 0,"max": 100,"default": 0,"unit": "%"},{"name": "to","type": "number","min": 0,"max": 100,"default": 100,"unit": "%"},{"name": "feedback","type": "text","label": "Feedback for defined score range","importance": "low","placeholder": "Fill in the feedback","optional": true}]}}]},{"label": "Text for \"Show solutions\" button","name": "showSolutions","type": "text","default": "Show solution","common": true},{"label": "Text for \"Retry\" button","importance": "low","name": "tryAgain","type": "text","default": "Retry","common": true,"optional": true},{"label": "Text for \"Check\" button","importance": "low","name": "checkAnswer","type": "text","default": "Check","common": true,"optional": true},{"label": "Text for \"Not filled out\" message","importance": "low","name": "notFilledOut","type": "text","default": "Please fill in all blanks to view solution","common": true,"optional": true},{"label": "Text for \"\':ans\' is correct\" message","importance": "low","name": "answerIsCorrect","type": "text","default": "\':ans\' is correct","common": true,"optional": true},{"label": "Text for \"\':ans\' is wrong\" message","importance": "low","name": "answerIsWrong","type": "text","default": "\':ans\' is wrong","common": true,"optional": true},{"label": "Text for \"Answered correctly\" message","importance": "low","name": "answeredCorrectly","type": "text","default": "Answered correctly","common": true,"optional": true},{"label": "Text for \"Answered incorrectly\" message","importance": "low","name": "answeredIncorrectly","type": "text","default": "Answered incorrectly","common": true,"optional": true},{"label": "Assistive technology label for solution","importance": "low","name": "solutionLabel","type": "text","default": "Correct answer:","common": true,"optional": true},{"label": "Assistive technology label for input field","importance": "low","name": "inputLabel","type": "text","description": "Use @num and @total to replace current cloze number and total cloze number","default": "Blank input @num of @total","common": true,"optional": true},{"label": "Assistive technology label for saying an input has a tip tied to it","importance": "low","name": "inputHasTipLabel","type": "text","default": "Tip available","common": true,"optional": true},{"label": "Tip icon label","importance": "low","name": "tipLabel","type": "text","default": "Tip","common": true,"optional": true},{"name": "behaviour","type": "group","label": "Behavioural settings.","importance": "low","description": "These options will let you control how the task behaves.","optional": true,"fields": [{"label": "Enable \"Retry\"","importance": "low","name": "enableRetry","type": "boolean","default": true,"optional": true},{"label": "Enable \"Show solution\" button","importance": "low","name": "enableSolutionsButton","type": "boolean","default": true,"optional": true},{"name": "enableCheckButton","type": "boolean","label": "Enable \"Check\" button","widget": "none","importance": "low","default": true,"optional": true},{"label": "Automatically check answers after input","importance": "low","name": "autoCheck","type": "boolean","default": false,"optional": true},{"name": "caseSensitive","importance": "low","type": "boolean","default": true,"label": "Case sensitive","description": "Makes sure the user input has to be exactly the same as the answer."},{"label": "Require all fields to be answered before the solution can be viewed","importance": "low","name": "showSolutionsRequiresInput","type": "boolean","default": true,"optional": true},{"label": "Put input fields on separate lines","importance": "low","name": "separateLines","type": "boolean","default": false,"optional": true},{"label": "Disable image zooming for question image","importance": "low","name": "disableImageZooming","type": "boolean","default": false,"optional": true},{"label": "Show confirmation dialog on \"Check\"","importance": "low","name": "confirmCheckDialog","type": "boolean","description": "This options is not compatible with the \"Automatically check answers after input\" option","default": false},{"label": "Show confirmation dialog on \"Retry\"","importance": "low","name": "confirmRetryDialog","type": "boolean","default": false},{"name": "acceptSpellingErrors","type": "boolean","label": "Accept minor spelling errors","importance": "low","description": "If activated, an answer will also count as correct with minor spelling errors (3-9 characters: 1 spelling error, more than 9 characters: 2 spelling errors)","default": false,"optional": true}]},{"label": "Check confirmation dialog","importance": "low","name": "confirmCheck","type": "group","common": true,"fields": [{"label": "Header text","importance": "low","name": "header","type": "text","default": "Finish ?"},{"label": "Body text","importance": "low","name": "body","type": "text","default": "Are you sure you wish to finish ?","widget": "html","enterMode": "p","tags": ["strong","em","del","u"]},{"label": "Cancel button label","importance": "low","name": "cancelLabel","type": "text","default": "Cancel"},{"label": "Confirm button label","importance": "low","name": "confirmLabel","type": "text","default": "Finish"}]},{"label": "Retry confirmation dialog","importance": "low","name": "confirmRetry","type": "group","common": true,"fields": [{"label": "Header text","importance": "low","name": "header","type": "text","default": "Retry ?"},{"label": "Body text","importance": "low","name": "body","type": "text","default": "Are you sure you wish to retry ?","widget": "html","enterMode": "p","tags": ["strong","em","del","u"]},{"label": "Cancel button label","importance": "low","name": "cancelLabel","type": "text","default": "Cancel"},{"label": "Confirm button label","importance": "low","name": "confirmLabel","type": "text","default": "Confirm"}]},{"name": "scoreBarLabel","type": "text","label": "Textual representation of the score bar for those using a readspeaker","default": "You got :num out of :total points","importance": "low","common": true}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => 34,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.Image',
                    'title' => 'Image',
                    'major_version' => 1,
                    'minor_version' => 1,
                    'patch_version' => 8,
                    'runnable' => 0,
                    'restricted' => 0,
                    'fullscreen' => 0,
                    'embed_types' => "",
                    'preloaded_js' => 'image.js',
                    'preloaded_css' => 'image.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"name": "file","type": "image","label": "Image","importance": "high","disableCopyright": true},{"name": "alt","type": "text","label": "Alternative text","importance": "high","description": "Required. If the browser cant load the image this text will be displayed instead. Also used by \"text-to-speech\" readers."},{"name": "title","type": "text","label": "Hover text","importance": "low","description": "Optional. This text is displayed when the users hover their pointing device over the image.","optional": true},{"name": "contentName","type": "text","label": "Image content name","importance": "low","common": true,"default": "Image"}]',
                    'tutorial_url' => '',
                    'metadata_settings' => '{\"disable\":false,\"disableExtraTitleField\":true}',
                ],
                [
                    'id' => 35,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.Image',
                    'title' => 'Image',
                    'major_version' => 1,
                    'minor_version' => 0,
                    'patch_version' => 32,
                    'runnable' => 0,
                    'restricted' => 0,
                    'fullscreen' => 0,
                    'embed_types' => "",
                    'preloaded_js' => 'image.js',
                    'preloaded_css' => 'image.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"name":"file","type":"image","label":"Image","importance":"high"},{"name":"alt","type":"text","label":"Alternative text","importance":"high","description":"Required. If the browser cant load the image this text will be displayed instead. Also used by readspeakers."},{"name":"title","type":"text","label":"Hover text","importance":"low","description":"Optional. This text is displayed when the user hovers his pointing device over the image.","optional":true},{"name":"copyright","type":"group","importance":"low","label":"Copyright information","deprecated":true,"optional":true,"fields":[{"name":"title","type":"text","label":"Title","placeholder":"La Gioconda","optional":true},{"name":"author","type":"text","label":"Author","placeholder":"Leonardo da Vinci","optional":true},{"name":"source","type":"text","label":"Source","placeholder":"http://en.wikipedia.org/wiki/Mona_Lisa","optional":true,"regexp":{"pattern":"^http[s]?://.+","modifiers":"i"}},{"name":"license","type":"select","label":"License","default":"U","options":[{"value":"U","label":"Undisclosed"},{"value":"CC BY","label":"Attribution"},{"value":"CC BY-SA","label":"Attribution-ShareAlike"},{"value":"CC BY-ND","label":"Attribution-NoDerivs"},{"value":"CC BY-NC","label":"Attribution-NonCommercial"},{"value":"CC BY-NC-SA","label":"Attribution-NonCommercial-ShareAlike"},{"value":"CC BY-NC-ND","label":"Attribution-NonCommercial-NoDerivs"},{"value":"GNU GPL","label":"General Public License"},{"value":"PD","label":"Public Domain"},{"value":"ODC PDDL","label":"Public Domain Dedication and Licence"},{"value":"CC PDM","label":"Public Domain Mark"},{"value":"C","label":"Copyright"}]}]},{"name":"contentName","type":"text","label":"Image content name","importance":"low","common":true,"default":"Image"}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
                [
                    'id' => 220,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'name' => 'H5P.Summary',
                    'title' => 'Summary',
                    'major_version' => 1,
                    'minor_version' => 8,
                    'patch_version' => 4,
                    'runnable' => 1,
                    'restricted' => 0,
                    'fullscreen' => 0,
                    'embed_types' => "iframe",
                    'preloaded_js' => 'js/stop-watch.js, js/xapi-event-builder.js, js/summary.js',
                    'preloaded_css' => 'css/summary.css',
                    'drop_library_css' => '',
                    'semantics' => '[{"name": "intro","type": "text","widget": "html","label": "Introduction text","importance": "high","default": "Choose the correct statement.","description": "Will be displayed above the summary task.","enterMode": "p","tags": ["strong","em","u","a","ul","ol","h2","h3","hr"],"common": false},{"name": "summaries","importance": "high","type": "list","widgets": [{"name": "ListEditor","label": "Default"},{"name": "SummaryTextualEditor","label": "Textual"}],"label": "Summary","entity": "statements","max": 100,"min": 1,"field": {"name": "statements","type": "group","label": "Set of statements","importance": "high","isSubContent": true,"fields": [{"name": "summary","type": "list","label": "List of statements for the summary - the first statement is correct.","entity": "statement","importance": "medium","min": 2,"field": {"name": "text","type": "text","label": "Statement","importance": "medium","widget": "html","enterMode": "p","tags": []}},{"name": "tip","type": "group","label": "Tip","importance": "low","optional": true,"fields": [{"name": "tip","label": "Tip text","importance": "low","type": "text","widget": "html","tags": ["p","br","strong","em"],"optional": true}]}]}},{"name": "overallFeedback","type": "group","label": "Overall Feedback","importance": "low","expanded": true,"fields": [{"name": "overallFeedback","type": "list","widgets": [{"name": "RangeList","label": "Default"}],"importance": "high","label": "Define custom feedback for any score range","description": "Click the \"Add range\" button to add as many ranges as you need. Example: 0-20% Bad score, 21-91% Average Score, 91-100% Great Score!","entity": "range","min": 1,"defaultNum": 1,"optional": true,"field": {"name": "overallFeedback","type": "group","importance": "low","fields": [{"name": "from","type": "number","label": "Score Range","min": 0,"max": 100,"default": 0,"unit": "%"},{"name": "to","type": "number","min": 0,"max": 100,"default": 100,"unit": "%"},{"name": "feedback","type": "text","label": "Feedback for defined score range","importance": "low","placeholder": "Fill in the feedback","optional": true}]}}]},{"name": "solvedLabel","type": "text","label": "Text displayed before number of statements solved in the summary task.","importance": "low","default": "Progress:","description": "Will be displayed above the statements. Example: Progress: 2/5","common": true},{"name": "scoreLabel","type": "text","label": "Text displayed before number of wrong statements selected in the summary task.","importance": "low","default": "Wrong answers:","description": "Will be displayed above the statements. Example: Wrong answers: 4","common": true},{"name": "resultLabel","type": "text","label": "Summary feedback header","importance": "low","default": "Your result","description": "Will be displayed above the summary feedback.","common": true},{"name": "labelCorrect","type": "text","label": "Readspeaker text for correct answer","importance": "low","default": "Correct.","common": true},{"name": "labelIncorrect","type": "text","label": "Readspeaker text for incorrect answer","importance": "low","default": "Incorrect! Please try again.","common": true},{"name": "labelCorrectAnswers","type": "text","label": "Label list of correct answers","importance": "low","default": "Correct answers.","common": true},{"name": "tipButtonLabel","type": "text","label": "Label for the show tip button","importance": "low","default": "Show tip","common": true},{"name": "scoreBarLabel","type": "text","label": "Textual representation of the score bar for those using a readspeaker","description": ":num and :total are special keywords which are programmatically updated","default": "You got :num out of :total points","importance": "low","common": true},{"name": "progressText","type": "text","label": "Text used for readspeakers to communicate progress","description": ":num and :total are special keywords which are programmatically updated","default": "Progress :num of :total","importance": "low","common": true}]',
                    'tutorial_url' => '',
                    'metadata_settings' => null,
                ],
            ],
        );
    }

    public function h5pLibrariesLibraries()
    {
        DB::table("h5p_libraries_libraries")->insert(
            [
                ['library_id' => '1', 'required_library_id' => '76', 'dependency_type' => 'preloaded'],
                ['library_id' => '72', 'required_library_id' => '3', 'dependency_type' => 'preloaded'],
                ['library_id' => '192', 'required_library_id' => '72', 'dependency_type' => 'editor'],
                ['library_id' => '192', 'required_library_id' => '86', 'dependency_type' => 'preloaded'],
                ['library_id' => '192', 'required_library_id' => '140', 'dependency_type' => 'preloaded'],
                ['library_id' => '37', 'required_library_id' => '1', 'dependency_type' => 'preloaded'],
                ['library_id' => '37', 'required_library_id' => '3', 'dependency_type' => 'preloaded'],
                ['library_id' => '37', 'required_library_id' => '54', 'dependency_type' => 'preloaded'],
                ['library_id' => '43', 'required_library_id' => '3', 'dependency_type' => 'preloaded'],
                ['library_id' => '43', 'required_library_id' => '37', 'dependency_type' => 'preloaded'],
                ['library_id' => '207', 'required_library_id' => '3', 'dependency_type' => 'preloaded'],
                ['library_id' => '207', 'required_library_id' => '121', 'dependency_type' => 'preloaded'],
                ['library_id' => '207', 'required_library_id' => '181', 'dependency_type' => 'editor'],
                ['library_id' => '207', 'required_library_id' => '208', 'dependency_type' => 'preloaded'],
                ['library_id' => '39', 'required_library_id' => '3', 'dependency_type' => 'preloaded'],
                ['library_id' => '39', 'required_library_id' => '37', 'dependency_type' => 'preloaded'],
                ['library_id' => '39', 'required_library_id' => '43', 'dependency_type' => 'preloaded'],
                ['library_id' => '90', 'required_library_id' => '3', 'dependency_type' => 'preloaded'],
                ['library_id' => '90', 'required_library_id' => '37', 'dependency_type' => 'preloaded'],
                ['library_id' => '90', 'required_library_id' => '92', 'dependency_type' => 'preloaded'],
                ['library_id' => '284', 'required_library_id' => '34', 'dependency_type' => 'preloaded'],
                ['library_id' => '202', 'required_library_id' => '35', 'dependency_type' => 'preloaded'],
                ['library_id' => '202', 'required_library_id' => '220', 'dependency_type' => 'preloaded'],
            ],
        );
    }
}
