process.env.EDLIBCOMMON_EXTERNALAUTH_ADAPTER_AUTH0_DOMAIN = 'test.com';
process.env.EDLIBCOMMON_EXTERNALAUTH_ADAPTER_AUTH0_CLIENTID = '1';
process.env.EDLIBCOMMON_EXTERNALAUTH_ADAPTER_AUTH0_AUDIENCE = 'somebody';
