{{- template "helpers.initJob" (dict "name" "authapi" "image" "ghcr.io/cerpus/edlib/api-auth-migration" "imageTag" .Chart.AppVersion ) }}
---
{{- template "helpers.service" (dict "name" "authapi") }}
---
{{- template "helpers.deployment" (dict "name" "authapi" "image" "ghcr.io/cerpus/edlib/api-auth-app" "imageTag" .Chart.AppVersion "replicaCount" 1  "healthUrl" "/_ah/health?probe=readiness" ) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "authapi" ) }}
