{{- template "helpers.initJob" (dict "name" "authapi" "image" "public.ecr.aws/f0t8l9h1/api-auth-migration" "imageTag" .Chart.AppVersion ) }}
---
{{- template "helpers.service" (dict "name" "authapi") }}
---
{{- template "helpers.deployment" (dict "name" "authapi" "image" "public.ecr.aws/f0t8l9h1/api-auth-app" "imageTag" .Chart.AppVersion "replicaCount" .Values.minReplicaCount  "healthUrl" "/_ah/health" "fluentdParser" "node-json" "slowStartMaxTimeSeconds" 60 ) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "authapi" "minReplicaCount" .Values.minReplicaCount ) }}
---
{{- template "helpers.podDisruptionBudget" (dict "name" "authapi" ) }}
