{{- template "helpers.initJob" (dict "name" "commonapi" "image" "ghcr.io/cerpus/edlib/api-common-migration" "imageTag" .Chart.AppVersion ) }}
---
{{- template "helpers.service" (dict "name" "commonapi") }}
---
{{- template "helpers.phpDeployment" (dict "name" "commonapi" "proxyImage" "ghcr.io/cerpus/edlib/api-common-web" "fpmImage" "ghcr.io/cerpus/edlib/api-common-fpm" "imageTag" .Chart.AppVersion "replicaCount" 1 ) }}
