kind: Job
apiVersion: batch/v1
metadata:
  name: commonapi-startup
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: startup
          image: "public.ecr.aws/f0t8l9h1/api-common-migration:{{ .Chart.AppVersion }}"
          env:
{{- include "common.envBlock" ( dict "Global" . "containerEnv" true ) | indent 12 }}
---
{{- template "helpers.service" (dict "name" "commonapi") }}
---
{{- template "helpers.phpDeployment" (dict "name" "commonapi" "proxyImage" "public.ecr.aws/f0t8l9h1/api-common-web" "fpmImage" "public.ecr.aws/f0t8l9h1/api-common-fpm" "imageTag" .Chart.AppVersion "replicaCount" .Values.minReplicaCount  "healthUrl" "/internal/health" "fluentdParser" "laravel-json" ) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "commonapi" "minReplicaCount" .Values.minReplicaCount ) }}
---
{{- template "helpers.podDisruptionBudget" (dict "name" "commonapi" ) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-rabbitmq-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-rabbitmq-subscriber
  template:
    metadata:
      labels:
        app: common-rabbitmq-subscriber
        fluentd-parser: laravel-json
    spec:
      containers:
        - name: main
          image: "public.ecr.aws/f0t8l9h1/api-common-fpm:{{ .Chart.AppVersion }}"
          command:
            - php
            - artisan
            - laravel-rabbitmq-pubsub:consumer
          envFrom:
            - configMapRef:
                name: common-v2
                optional: false
            - secretRef:
                name: common-v2
                optional: false
          resources:
            limits:
              cpu: 500m
              memory: 1500Mi
            requests:
              cpu: 20m
              memory: 200Mi
