{{- template "helpers.initJob" (dict "name" "contentauthor" "image" "ghcr.io/cerpus/edlib/api-contentauthor-deploy" "imageTag" .Chart.AppVersion "envFromConfig" (list "ca-config") "envFromSecret" (list "ca-secret") ) }}
---
{{- template "helpers.service" (dict "name" "contentauthor" "port" 8081) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "contentauthor" ) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contentauthor
spec:
  selector:
    matchLabels:
      app: contentauthor
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: contentauthor
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - contentauthor
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
        - name: main
          image: "ghcr.io/cerpus/edlib/api-contentauthor-app:{{ .Chart.AppVersion }}"
          env:
            - name: STARTUP_CONTAINER_ENABLED
              value: "1"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: ca-secret
                optional: true
            - configMapRef:
                name: ca-config
                optional: true
            - configMapRef:
                name: common-config
                optional: false
            - secretRef:
                name: common-secret
                optional: false
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 1500Mi
            requests:
              cpu: 20m
              memory: 200Mi
          startupProbe:
            failureThreshold: 100
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /storage
              name: storage-ca
        - name: cron
          image: "ghcr.io/cerpus/edlib/api-contentauthor-cron:{{ .Chart.AppVersion }}"
          env:
            - name: STARTUP_CONTAINER_ENABLED
              value: "1"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: ca-secret
                optional: true
            - configMapRef:
                name: ca-config
                optional: true
            - configMapRef:
                name: common-config
                optional: false
            - secretRef:
                name: common-secret
                optional: false
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /storage
              name: storage-ca
        - name: edstepmessages
          image: "ghcr.io/cerpus/edlib/api-contentauthor-edstepmessages:{{ .Chart.AppVersion }}"
          env:
            - name: STARTUP_CONTAINER_ENABLED
              value: "1"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: ca-secret
                optional: true
            - configMapRef:
                name: ca-config
                optional: true
            - configMapRef:
                name: common-config
                optional: false
            - secretRef:
                name: common-secret
                optional: false
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /storage
              name: storage-ca
        - name: horizonqueue
          image: "ghcr.io/cerpus/edlib/api-contentauthor-horizonqueue:{{ .Chart.AppVersion }}"
          env:
            - name: STARTUP_CONTAINER_ENABLED
              value: "1"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: ca-secret
                optional: true
            - configMapRef:
                name: ca-config
                optional: true
            - configMapRef:
                name: common-config
                optional: false
            - secretRef:
                name: common-secret
                optional: false
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /storage
              name: storage-ca
        - name: phpfpm
          image: "ghcr.io/cerpus/edlib/api-contentauthor-phpfpm:{{ .Chart.AppVersion }}"
          env:
            - name: STARTUP_CONTAINER_ENABLED
              value: "1"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: ca-secret
                optional: true
            - configMapRef:
                name: ca-config
                optional: true
            - configMapRef:
                name: common-config
                optional: false
            - secretRef:
                name: common-secret
                optional: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /storage
              name: storage-ca
      initContainers:
        - name: init
          image: "ghcr.io/cerpus/edlib/api-contentauthor-init:{{ .Chart.AppVersion }}"
          env:
            - name: STARTUP_CONTAINER_ENABLED
              value: "0"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: ca-secret
                optional: true
            - configMapRef:
                name: ca-config
                optional: true
            - configMapRef:
                name: common-config
                optional: false
            - secretRef:
                name: common-secret
                optional: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /storage
              name: storage-ca
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: contentauthor
      serviceAccountName: contentauthor
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: storage-ca
