{{- template "helpers.initJob" (dict "name" "licenseapi" "image" "ghcr.io/cerpus/edlib/api-license-migration" "imageTag" .Chart.AppVersion "envFromConfig" (list "licenseapi-config") "envFromSecret" (list "licenseapi-secret") ) }}
---
{{- template "helpers.service" (dict "name" "licenseapi") }}
---
{{- template "helpers.deployment" (dict "name" "licenseapi" "image" "ghcr.io/cerpus/edlib/api-license-web" "initImage" "ghcr.io/cerpus/edlib/api-license-init" "imageTag" .Chart.AppVersion "envFromConfig" (list "licenseapi-config") "envFromSecret" (list "licenseapi-secret") "replicaCount" 1  "healthUrl" "/_ah/health" ) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "licenseapi" ) }}
