kind: Job
apiVersion: batch/v1
metadata:
  name: ltiapi-startup
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: startup
          image: "public.ecr.aws/f0t8l9h1/api-lti-migration:{{ .Chart.AppVersion }}"
          env:
{{- include "common.envBlock" ( dict "Global" . "containerEnv" true ) | indent 12 }}
---
{{- template "helpers.service" (dict "name" "ltiapi") }}
---
{{- template "helpers.deployment" (dict "name" "ltiapi" "image" "public.ecr.aws/f0t8l9h1/api-lti-app" "imageTag" .Chart.AppVersion "replicaCount" .Values.minReplicaCount  "healthUrl" "/_ah/health" "fluentdParser" "node-json" ) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "ltiapi" "minReplicaCount" .Values.minReplicaCount ) }}
---
{{- template "helpers.podDisruptionBudget" (dict "name" "ltiapi" ) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ltiapi-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ltiapi-subscriber
  template:
    metadata:
      labels:
        app: ltiapi-subscriber
        fluentd-parser: node-json
    spec:
      containers:
        - name: main
          image: "public.ecr.aws/f0t8l9h1/api-lti-app:{{ .Chart.AppVersion }}"
          command:
            - yarn
            - start:subscribers
          envFrom:
            - configMapRef:
                name: common-v2
                optional: false
            - secretRef:
                name: common-v2
                optional: false
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "150m"
