{{- template "helpers.initJob" (dict "name" "resourceapi" "image" "public.ecr.aws/f0t8l9h1/api-resources-migration" "imageTag" .Chart.AppVersion ) }}
---
{{- template "helpers.service" (dict "name" "resourceapi") }}
---
{{- template "helpers.deployment" (dict "name" "resourceapi" "image" "public.ecr.aws/f0t8l9h1/api-resources-app" "imageTag" .Chart.AppVersion "replicaCount" .Values.minReplicaCount  "healthUrl" "/_ah/health" "fluentdParser" "node-json" ) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "resourceapi" "minReplicaCount" .Values.minReplicaCount ) }}
---
{{- template "helpers.podDisruptionBudget" (dict "name" "resourceapi" ) }}
