{{- template "helpers.initJob" (dict "name" "resourceapi" "image" "ghcr.io/cerpus/edlib/api-resources-migration" "imageTag" .Chart.AppVersion ) }}
---
{{- template "helpers.service" (dict "name" "resourceapi") }}
---
{{- template "helpers.deployment" (dict "name" "resourceapi" "image" "ghcr.io/cerpus/edlib/api-resources-app" "imageTag" .Chart.AppVersion "replicaCount" .Values.minReplicaCount  "healthUrl" "/_ah/health" ) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "resourceapi" "minReplicaCount" .Values.minReplicaCount ) }}
---
{{- template "helpers.podDisruptionBudget" (dict "name" "resourceapi" ) }}
