{{- template "helpers.initJob" (dict "name" "resourceapi" "image" "ghcr.io/cerpus/edlib/api-resources-migration" "imageTag" .Chart.Version ) }}
---
{{- template "helpers.service" (dict "name" "resourceapi") }}
---
{{- template "helpers.deployment" (dict "name" "resourceapi" "image" "ghcr.io/cerpus/edlib/api-resources-app" "imageTag" .Chart.Version "replicaCount" 1 ) }}
