{{- template "helpers.initJob" (dict "name" "urlapi" "image" "ghcr.io/cerpus/edlib/api-url-migration" "imageTag" .Chart.AppVersion ) }}
---
{{- template "helpers.service" (dict "name" "urlapi") }}
---
{{- template "helpers.deployment" (dict "name" "urlapi" "image" "ghcr.io/cerpus/edlib/api-url-app" "imageTag" .Chart.AppVersion "replicaCount" 1 "healthUrl" "/_ah/health" ) }}
