{{- template "helpers.initJob" (dict "name" "urlapi" "image" "ghcr.io/cerpus/edlib/api-url-migration" "imageTag" .Chart.Version ) }}
---
{{- template "helpers.service" (dict "name" "urlapi") }}
---
{{- template "helpers.deployment" (dict "name" "urlapi" "image" "ghcr.io/cerpus/edlib/api-url-app" "imageTag" .Chart.Version "replicaCount" 1 ) }}
