kind: Job
apiVersion: batch/v1
metadata:
  name: urlapi-startup
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: startup
          image: "public.ecr.aws/f0t8l9h1/api-url-migration:{{ .Chart.AppVersion }}"
          env:
  {{- include "common.envBlock" ( dict "Global" . "containerEnv" true ) | indent 12 }}
---
{{- template "helpers.service" (dict "name" "urlapi") }}
---
{{- template "helpers.deployment" (dict "name" "urlapi" "image" "public.ecr.aws/f0t8l9h1/api-url-app" "imageTag" .Chart.AppVersion "replicaCount" .Values.minReplicaCount "healthUrl" "/_ah/health" "fluentdParser" "node-json" ) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "urlapi" "minReplicaCount" .Values.minReplicaCount ) }}
---
{{- template "helpers.podDisruptionBudget" (dict "name" "urlapi" ) }}
