{{- template "helpers.service" (dict "name" "proxy-admin") }}
---
{{- template "helpers.deployment" (dict "name" "proxy-admin" "image" "ghcr.io/cerpus/edlib/proxy-admin-app" "imageTag" .Chart.Version "replicaCount" 1 "healthUrl" "/" ) }}
