{{- template "helpers.service" (dict "name" "proxy-auth") }}
---
{{- template "helpers.deployment" (dict "name" "proxy-auth" "image" "ghcr.io/cerpus/edlib/proxy-auth-app" "imageTag" .Chart.AppVersion "replicaCount" .Values.minReplicaCount "healthUrl" "/_ah/health" ) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "proxy-auth" "minReplicaCount" .Values.minReplicaCount ) }}
---
{{- template "helpers.podDisruptionBudget" (dict "name" "proxy-auth" ) }}
