{{- template "helpers.service" (dict "name" "proxy-lti") }}
---
{{- template "helpers.deployment" (dict "name" "proxy-lti" "image" "ghcr.io/cerpus/edlib/proxy-lti-app" "imageTag" .Chart.AppVersion "replicaCount" 1 "healthUrl" "/resources/_ah/health?probe=readiness" ) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "proxy-lti" ) }}
