{{- template "helpers.service" (dict "name" "proxy-lti") }}
---
{{- template "helpers.deployment" (dict "name" "proxy-lti" "image" "ghcr.io/cerpus/edlib/proxy-lti-app" "imageTag" .Chart.AppVersion "replicaCount" .Values.minReplicaCount "healthUrl" "/_ah/health" ) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "proxy-lti" "minReplicaCount" .Values.minReplicaCount ) }}
---
{{- template "helpers.podDisruptionBudget" (dict "name" "proxy-lti" ) }}
