{{- template "helpers.service" (dict "name" "proxy-lti") }}
---
{{- template "helpers.deployment" (dict "name" "proxy-lti" "image" "public.ecr.aws/f0t8l9h1/proxy-lti-app" "imageTag" .Chart.AppVersion "replicaCount" .Values.minReplicaCount "healthUrl" "/_ah/health" "fluentdParser" "node-json" ) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "proxy-lti" "minReplicaCount" .Values.minReplicaCount ) }}
---
{{- template "helpers.podDisruptionBudget" (dict "name" "proxy-lti" ) }}
