{{- template "helpers.service" (dict "name" "proxy-resource") }}
---
{{- template "helpers.deployment" (dict "name" "proxy-resource" "image" "public.ecr.aws/f0t8l9h1/proxy-resource-app" "imageTag" .Chart.AppVersion "replicaCount" .Values.minReplicaCount "healthUrl" "/_ah/health" "fluentdParser" "node-json" ) }}
---
{{- template "helpers.horizontalPodAutoscaler" (dict "name" "proxy-resource" "minReplicaCount" .Values.minReplicaCount ) }}
---
{{- template "helpers.podDisruptionBudget" (dict "name" "proxy-resource" ) }}
