name: "API - Content Author"

on:
  push:
    paths:
      - "sourcecode/apis/contentauthor/**"
      - ".github/workflows/api-contentauthor.yaml"
  workflow_call:
    inputs:
      versionToRelease:
        description: 'A version to release'
        required: true
        type: string

env:
  workingDirectory: sourcecode/apis/contentauthor

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build test image
        run: |
          cd ${{ env.workingDirectory }}
          docker buildx build -t contentauthor-test .

      - name: Run tests
        run: |
          cd ${{ env.workingDirectory }}
          mkdir -p test-storage-volume
          docker run contentauthor-test

#      - name: Upload artifacts
#        uses: actions/upload-artifact@master
#        if: failure()
#        with:
#          name: Logs
#          path: ${{ env.workingDirectory }}/test-storage-volume
#
#  create_release:
#    runs-on: ubuntu-latest
#    needs: test
#    if: github.event_name == 'workflow_dispatch'
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Login to GitHub docker registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ github.token }}
#
#      - name: Build and push web container
#        id: docker_build_web
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: ghcr.io/cerpus/edlib/api-contentauthor-web:${{ inputs.versionToRelease }}
#          context: sourcecode/apis/contentauthor
#          target: web
#
#      - name: Build and push fpm container
#        id: docker_build_fpm
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: ghcr.io/cerpus/edlib/api-contentauthor-fpm:${{ inputs.versionToRelease }}
#          context: sourcecode/apis/contentauthor
#          target: prod
#
#      - name: Build and push migration container
#        id: docker_build_migration
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: ghcr.io/cerpus/edlib/api-contentauthor-migration:${{ inputs.versionToRelease }}
#          context: sourcecode/apis/contentauthor
#          target: deploy
