name: "api-doku"

on:
  push:
    paths:
      - "sourcecode/apis/doku/**"
      - ".github/workflows/api-doku.yaml"

env:
  workingDirectory: sourcecode/apis/doku

jobs:
  build_test_pushdocker:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 14
          uses: actions/setup-node@v2
          with:
            node-version: 14
        - name: "Yarn install"
          run: cd ${{ env.workingDirectory }}; yarn
          shell: bash
        - name: "Run tests"
          run: cd ${{ env.workingDirectory }}; yarn test
          shell: bash

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: docker.pkg.github.com/cerpus/edlib/api-doku:${{ github.sha }},docker.pkg.github.com/cerpus/edlib/api-doku:latest
            context: sourcecode/apis/doku
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
