name: "api-auth"

on:
  push:
    paths:
      - "versions/**"
      - "sourcecode/apis/auth/**"
      - ".github/workflows/api-auth.yaml"

env:
  workingDirectory: sourcecode/apis/auth

jobs:
  build_test_pushdocker:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Use Node.js 14
          uses: actions/setup-node@v2
          with:
            node-version: 14

        - name: Get specific changed files
          id: changed-files
          uses: tj-actions/changed-files@v6.3
          with:
            files: |
              versions/beta
              versions/official

        - name: Get release name
          id: releaseName
          uses: ./.github/actions/nodeJsApi

        - name: Run step when a file changes
          if: contains(steps.changed-files.outputs.modified_files, 'versions/beta')
          run: |
            echo "Deploy new beta version"

#        - name: "Yarn install with cache"
#          uses: bahmutov/npm-install@v1
#          with:
#            working-directory: ${{ env.workingDirectory }}
#        - name: "Run tests"
#          run: cd ${{ env.workingDirectory }}; yarn test
#          shell: bash
#
#        - name: Set up Docker Buildx
#          uses: docker/setup-buildx-action@v1
#        - name: Login to GitHub docker registry
#          uses: docker/login-action@v1
#          with:
#            registry: ghcr.io
#            username: ${{ github.actor }}
#            password: ${{ secrets.GITHUB_TOKEN }}
#        - name: Build and push app
#          id: docker_build_app
#          uses: docker/build-push-action@v2
#          with:
#            push: true
#            tags: ghcr.io/cerpus/edlib/api-auth-app:${{ steps.releaseName.outputs.release-name }}
#            context: sourcecode/apis/auth
#            target: prod
#        - name: Build and push migration container
#          id: docker_build_migration
#          uses: docker/build-push-action@v2
#          with:
#            push: true
#            tags: ghcr.io/cerpus/edlib/api-auth-migration:${{ steps.releaseName.outputs.release-name }}
#            context: sourcecode/apis/auth
#            target: migrations
#        - name: Image digest
#          run: echo ${{ steps.docker_build.outputs.digest }}
