name: "Auto release"

on:
  push:
    branches:
      - master

jobs:
  create_release:
    needs: get_variables
    uses: cerpus/Edlib/.github/workflows/create-release.yaml@auto_deploy_to_test
    secrets:
      AWS_DOCKER_REGISTRY_ACCESS_KEY_ID: ${{ secrets.AWS_DOCKER_REGISTRY_ACCESS_KEY_ID }}
      AWS_DOCKER_REGISTRY_SECRET_ACCESS_KEY: ${{ secrets.AWS_DOCKER_REGISTRY_SECRET_ACCESS_KEY }}
