name: "aws-cerpus_dev"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true

jobs:
  deploy:
    environment: "aws_cerpus_dev"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy name
        run: |
          echo "Version to deploy: ${{ github.event.inputs.version }}"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: GithubCerpusDevDeploy

      - name: Update kubeconfig with cluster info
        run: |
          aws eks --region eu-west-1 update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER_NAME}}

      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'edlib'
          namespace: 'edlib'
          chart: './chart'
          values: |
            foo: bar
          value-files: "chart/values.yaml"
