name: "AWS Deploy"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
      environment:
        description: 'Environment to deploy to'
        required: true
        default: "cerpus_test"

jobs:
  deploy:
    environment: "${{ github.event.inputs.environment }}"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy name
        run: |
          echo "Version to deploy: ${{ github.event.inputs.version }}"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: GithubCerpusDevDeploy

      - name: Update kubeconfig with cluster info
        id: kube
        run: |
          aws eks --region eu-west-1 update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER_NAME }}
          CONFIG="$(base64 -w 0 ${HOME}/.kube/config)"
          echo "::set-output name=config::$CONFIG"

      - name: Update Chart.yaml with correct app version
        run: |
          echo "" >> ./chart/Chart.yaml
          echo "appVersion: \"${{ github.event.inputs.version }}\"" >> ./chart/Chart.yaml
          cat ./chart/Chart.yaml

      - name: helm deploy
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: '${{ steps.kube.outputs.config }}'
        with:
          command: helm upgrade --wait --timeout 60m --cleanup-on-fail --install edlib --namespace edlib ./chart

      - name: Post message to slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"*<https:\/\/github.com\/cerpus\/Edlib|Edlib>*"}},{"type":"section","text":{"type":"mrkdwn","text":"Versjon *<https:\/\/github.com\/cerpus\/Edlib\/tree\/${{ github.event.inputs.version }}|${{ github.event.inputs.version }}>* er lagt ut i *${{ github.event.inputs.environment }}* av ${{ github.actor }}\nDu finner release note <https:\/\/github.com\/cerpus\/Edlib\/releases\/tag\/${{ github.event.inputs.version }}|her>."}}]}' ${{ secrets.SLACK_HOOK_URL }}

