name: "Create release"

on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: 'Name of release'
        required: false
        default: ''
  push:
    branches:
      - master
      - auto_deploy_to_test

jobs:
  get_variables:
    runs-on: ubuntu-latest
    outputs:
      releaseRef: ${{ steps.get_ref.outputs.releaseRef }}
    steps:
      - name: Get the ref
        id: get_ref
        run: |
          ref="${{ github.sha }}"
          if [ -n "${{ github.event.inputs.releaseName }}" ]; then
            if ! [[ "${{ github.event.inputs.releaseName }}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
              echo "version is not semver"
              exit 1
            fi

            ref="${{ github.event.inputs.releaseName }}"
          fi

          echo "::set-output name=releaseRef::$ref"

# ---------- APIS -----------------
  release_api_auth:
    needs: get_variables
    uses: cerpus/Edlib/.github/workflows/api-auth.yaml@master
    with:
      versionToRelease: ${{ needs.get_variables.outputs.releaseRef }}
    secrets:
      AWS_DOCKER_REGISTRY_ACCESS_KEY_ID: ${{ secrets.AWS_DOCKER_REGISTRY_ACCESS_KEY_ID }}
      AWS_DOCKER_REGISTRY_SECRET_ACCESS_KEY: ${{ secrets.AWS_DOCKER_REGISTRY_SECRET_ACCESS_KEY }}

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event.inputs.releaseName != ''
    needs:
      - release_api_auth
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Create tag
        uses: actions/github-script@v5
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ github.event.inputs.releaseName }}",
              sha: context.sha
            })

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/auto_deploy_to_test' }}
    needs:
      - create_release
    steps:
      - name: Deploy
        run: |
          echo "deploying"
