
name: "Create release"

on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: 'Name of release'
        required: false
        default: ''
  push:
    branches:
      - master

jobs:
  get_variables:
    if: ${{ github.event_name != 'push' || github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    outputs:
      releaseRef: ${{ steps.get_ref.outputs.releaseRef }}
    steps:
      - name: Get the ref
        id: get_ref
        run: |
          ref="${{ github.sha }}"
          if [ -n "${{ github.event.inputs.releaseName }}" ]; then
            if ! [[ "${{ github.event.inputs.releaseName }}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
              echo "version is not semver"
              exit 1
            fi

            ref="${{ github.event.inputs.releaseName }}"
          fi

          echo "::set-output name=releaseRef::$ref"

  # ---------- APIS -----------------
  build_image_hub:
    needs: get_variables
    uses: cerpus/Edlib/.github/workflows/test.yaml@master
    with:
      versionToRelease: ${{ needs.get_variables.outputs.releaseRef }}

  building_done:
    runs-on: ubuntu-latest
    needs:
      - build_image_hub
    steps:
      - name: "Done building images"
        run: |
          echo "Done building images"

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event.inputs.releaseName != ''
    needs:
      - building_done
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ github.event.inputs.releaseName }}",
              sha: context.sha
            })

#  auto_deploy:
#    needs:
#      - building_done
#      - get_variables
#    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.actor != 'dependabot[bot]' }}
#    strategy:
#      fail-fast: false
#      matrix:
#        environment:
#          - cerpus_test
#    environment: ${{ matrix.environment }}
#    concurrency: deploy-${{ matrix.environment }}
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Deploy
#        uses: ./.github/actions/awsDeploy
#        with:
#          version: ${{ needs.get_variables.outputs.releaseRef }}
#          environment: ${{ matrix.environment }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
#          AWS_EKS_CLUSTER_NAME: ${{ secrets.AWS_EKS_CLUSTER_NAME }}
#          SLACK_HOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
#          EXTRA_SLACK_HOOK_URL: ${{ secrets.EXTRA_SLACK_HOOK_URL }}
