on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environment_name:
        required: true
        type: string
      name:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      aws_role_to_assume:
        required: true

jobs:
  deploy:
    name: Deploy ${{ inputs.name }} to ${{ inputs.environment }}
    concurrency: deploy-${{ inputs.name }}-${{ inputs.environment }}
    runs-on: ubuntu-24.04

    steps:
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
        aws-region: eu-west-1
        role-to-assume: ${{ secrets.aws_role_to_assume }}
        role-duration-seconds: 3600
        role-session-name: GithubCerpusDevDeploy

     - name: Re-deploy docker-compose on Elastic Beanstalk
       run: |
         aws elasticbeanstalk update-environment \
          --environment-name ${{ inputs.environment_name }} \
          --version-label ${{ inputs.version }}
