name: "npm-nodeUtils"

on:
  push:
    paths:
      - "sourcecode/npm/nodeUtils/**"
      - ".github/workflows/npm-nodeUtils.yaml"
  workflow_dispatch:

defaults:
  run:
    working-directory: sourcecode/npm/nodeUtils

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Use Node.js 16
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: npm
            cache-dependency-path: sourcecode/npm/nodeUtils/yarn.lock

        - run: yarn install --frozen-lockfile

        - name: "Run tests"
          run: yarn test

        - uses: JS-DevTools/npm-publish@v2
          if: github.event_name != 'workflow_dispatch' && env.NPM_CERPUS_SECRET != ''
          env:
            NPM_CERPUS_SECRET: ${{ secrets.NPM_CERPUS_SECRET }}
          with:
            package: sourcecode/npm/nodeUtils/package.json
            token: ${{ secrets.NPM_CERPUS_SECRET }}
            access: public

        - name: "Set version in package.json"
          if: github.event_name == 'workflow_dispatch'
          run: npm version 0.0.0-${{ github.sha }}

        - uses: JS-DevTools/npm-publish@v2
          if: github.event_name == 'workflow_dispatch'
          with:
            package: sourcecode/npm/nodeUtils/package.json
            token: ${{ secrets.NPM_CERPUS_SECRET }}
            access: public
            tag: beta
