name: "npm-components"

on:
  push:
    paths:
      - "sourcecode/npm/components/**"
      - ".github/workflows/npm-components.yaml"
  workflow_dispatch:

env:
  workingDirectory: sourcecode/npm/components

jobs:
  publish-if-needed:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 14
          uses: actions/setup-node@v2
          with:
            node-version: 14
        - name: "Yarn install with cache"
          uses: bahmutov/npm-install@v1
          with:
            working-directory: ${{ env.workingDirectory }}
        - uses: JS-DevTools/npm-publish@v1
          if: github.event_name != 'workflow_dispatch' && env.NPM_CERPUS_SECRET != ''
          env:
            NPM_CERPUS_SECRET: ${{ secrets.NPM_CERPUS_SECRET }}
          with:
            package: sourcecode/npm/components/package.json
            token: ${{ secrets.NPM_CERPUS_SECRET }}
            access: public

        - name: "Set version in package.json"
          if: github.event_name == 'workflow_dispatch'
          run: cd ${{ env.workingDirectory }}; npm version 0.0.0-${{ github.sha }};

        - uses: JS-DevTools/npm-publish@v1
          if: github.event_name == 'workflow_dispatch'
          with:
            package: sourcecode/npm/components/package.json
            token: ${{ secrets.NPM_CERPUS_SECRET }}
            access: public
            tag: beta
