name: "npm-nodeUtils"

on:
  push:
    paths:
      - "sourcecode/npm/nodeUtils/**"
      - ".github/workflows/npm-nodeUtils.yaml"

env:
  workingDirectory: sourcecode/npm/nodeUtils

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 16
          uses: actions/setup-node@v2
          with:
            node-version: 16
        - name: "Yarn install with cache"
          uses: bahmutov/npm-install@v1
          with:
            working-directory: ${{ env.workingDirectory }}
        - name: "Run tests"
          run: cd ${{ env.workingDirectory }}; yarn test
          shell: bash
        - uses: JS-DevTools/npm-publish@v1
          if: env.NPM_CERPUS_SECRET != ''
          env:
            NPM_CERPUS_SECRET: ${{ secrets.NPM_CERPUS_SECRET }}
          with:
            package: sourcecode/npm/nodeUtils/package.json
            token: ${{ secrets.NPM_CERPUS_SECRET }}
            access: public
        - name: "Deploy beta components package to npm"
          if: github.ref == 'refs/heads/beta'
          run: cd ${{ env.workingDirectory }}; npm version 0.0.0-${{ github.sha }}; npm publish --tag beta
          env:
            INPUT_TOKEN: ${{ secrets.NPM_CERPUS_SECRET }}
