name: "npm-components"

on:
  push:
    paths:
      - "sourcecode/npm/components/**"
      - ".github/workflows/npm-components.yaml"

env:
  workingDirectory: sourcecode/npm/components

jobs:
  publish-if-needed:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 14
          uses: actions/setup-node@v2
          with:
            node-version: 14
        - name: "Yarn install"
          run: cd ${{ env.workingDirectory }}; yarn
          shell: bash
        - uses: JS-DevTools/npm-publish@v1
          with:
            package: sourcecode/npm/components/package.json
            token: ${{ secrets.NPM_CERPUS_SECRET }}
            access: public
