name: "Proxy - Url"

on:
  push:
    paths:
      - "sourcecode/proxies/url/**"
      - ".github/workflows/proxy-url.yaml"
  workflow_call:
    inputs:
      versionToRelease:
        description: 'A version to release'
        required: true
        type: string
    secrets:
      AWS_DOCKER_REGISTRY_ACCESS_KEY_ID:
        required: true
      AWS_DOCKER_REGISTRY_SECRET_ACCESS_KEY:
        required: true

env:
  workingDirectory: sourcecode/proxies/url

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: "Yarn install with cache"
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{ env.workingDirectory }}

      - name: "Run tests"
        run: cd ${{ env.workingDirectory }}; yarn test
        shell: bash

  create_release:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ inputs.versionToRelease && '1' || '0' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DOCKER_REGISTRY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DOCKER_REGISTRY_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-duration-seconds: 3600
          role-session-name: GithubCerpusPushImage

      - name: Login to AWS docker registry
        shell: bash
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build and push app
        id: docker_build_app
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: public.ecr.aws/f0t8l9h1/proxy-url-app:${{ inputs.versionToRelease }}
          context: sourcecode/proxies/url
          target: prod
