name: "proxy-iframe"

on:
  push:
    paths:
      - "versions/**"
      - "sourcecode/proxies/iframe/**"
      - ".github/workflows/proxy-iframe.yaml"

env:
  workingDirectory: sourcecode/proxies/iframe

jobs:
  check_if_should_release:
    runs-on: ubuntu-latest
    outputs:
      should-release: ${{ steps.release-after-check.outputs.should-release || 'no' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v6.3
        with:
          files: |
            versions/beta
            versions/official

      - name: Set should release to true if conditions are met
        id: release-after-check
        if: (contains(steps.changed-files.outputs.modified_files, 'versions/beta') && github.ref == 'refs/heads/beta') || (contains(steps.changed-files.outputs.modified_files, 'versions/official') && github.ref == 'refs/heads/master')
        run: |
          echo "::set-output name=should-release::yes"

  release:
    runs-on: ubuntu-latest
    needs: check_if_should_release
    if: needs.check_if_should_release.outputs.should-release == 'yes'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get release name
        id: releaseName
        uses: ./.github/actions/nodeJsApi

      - name: Display release name
        run: |
          echo "Releasing ${{ steps.releaseName.outputs.release-name }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app
        id: docker_build_app
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/cerpus/edlib/proxy-iframe-app:${{ steps.releaseName.outputs.release-name }}
          context: sourcecode/proxies/iframe
          target: prod

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
