name: "Proxy - Admin"

on:
  push:
    paths:
      - "sourcecode/proxies/admin/**"
      - ".github/workflows/proxy-admin.yaml"
  workflow_call:
    inputs:
      versionToRelease:
        description: 'A version to release'
        required: true
        type: string

env:
  workingDirectory: sourcecode/proxies/admin

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push app
        id: docker_build_app
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/cerpus/edlib/proxy-admin-app:${{ inputs.versionToRelease }}
          context: sourcecode/proxies/admin
          target: prod
