name: "proxy-url"

on:
  push:
    paths:
      - "sourcecode/proxies/url/**"
      - ".github/workflows/proxy-url.yaml"

env:
  workingDirectory: sourcecode/proxies/url

jobs:
  build_test_pushdocker:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 14
          uses: actions/setup-node@v2
          with:
            node-version: 14
        - name: "Yarn install with cache"
          uses: bahmutov/npm-install@v1
          with:
            working-directory: ${{ env.workingDirectory }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to GitHub docker registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push app
          id: docker_build_app
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ghcr.io/cerpus/edlib/proxy-url-app:${{ github.sha }}
            context: sourcecode/proxies/url
            target: prod
        - name: Image digest
          run: echo ${{ steps.docker_build_app.outputs.digest }}
